// lib/jurassicAIData.ts
// Jurassic Park (1993) script-driven data mapped from ontology JSON files.
// No generated / placeholder actors -- only the data from the JSON source files.

import type { CastingState } from "@/types/casting"

/* ------------------------------------------------------------------ */
/*  Predefined statuses (same as mockData)                             */
/* ------------------------------------------------------------------ */
const predefinedStatuses = [
  { id: "new", label: "New", bgColor: "bg-gray-200", textColor: "text-gray-700", category: "application", priority: 1, isCustom: false },
  { id: "applied", label: "Applied", bgColor: "bg-blue-200", textColor: "text-blue-700", category: "application", priority: 2, isCustom: false },
  { id: "interviewing", label: "Interviewing", bgColor: "bg-purple-200", textColor: "text-purple-700", category: "application", priority: 3, isCustom: false },
  { id: "offer", label: "Offer", bgColor: "bg-green-200", textColor: "text-green-700", category: "application", priority: 4, isCustom: false },
  { id: "rejected", label: "Rejected", bgColor: "bg-red-200", textColor: "text-red-700", category: "application", priority: 5, isCustom: false },
  { id: "closed", label: "Closed", bgColor: "bg-gray-400", textColor: "text-gray-900", category: "application", priority: 6, isCustom: false },
  { id: "contact-audition", label: "Audition Invited", bgColor: "bg-blue-100", textColor: "text-blue-800", category: "contact", priority: 1, isCustom: false },
  { id: "contact-callback", label: "Callback Invited", bgColor: "bg-green-100", textColor: "text-green-800", category: "contact", priority: 2, isCustom: false },
  { id: "contact-rejection", label: "Thanked", bgColor: "bg-gray-100", textColor: "text-gray-800", category: "contact", priority: 3, isCustom: false },
  { id: "contact-offer", label: "Offer Sent", bgColor: "bg-purple-100", textColor: "text-purple-800", category: "contact", priority: 4, isCustom: false },
  { id: "contact-general", label: "Contacted", bgColor: "bg-yellow-100", textColor: "text-yellow-800", category: "contact", priority: 5, isCustom: false },
]

/* ------------------------------------------------------------------ */
/*  Helper: empty actor lists for every character                      */
/* ------------------------------------------------------------------ */
const emptyActors = () => ({
  longList: [] as any[],
  shortLists: [] as any[],
  audition: [] as any[],
  approval: [] as any[],
})

/* ------------------------------------------------------------------ */
/*  Characters (from characters.json + requirements.json)              */
/* ------------------------------------------------------------------ */
const characters = [
  {
    id: "jb-alan-grant",
    name: "Dr. Alan Grant",
    description:
      "A world-renowned paleontologist in his mid-40s. Brilliant, physically capable, deeply uncomfortable around children. His journey from reluctant protector to surrogate father to Tim and Lex is the film's emotional spine. Must project both intellectual authority and physical action capability.",
    age: "40-50",
    gender: "Male",
    castingNotes:
      "Must balance scientific authority with action hero qualities. Conveys both skepticism and wonder. Physicality required for T-Rex jeep chase, tree-climbing, raptor kitchen sequence. Emotional range from distant academic to protective father figure. Top-line star or strong character actor with leading-man presence.",
    actors: emptyActors(),
  },
  {
    id: "jb-ellie-sattler",
    name: "Dr. Ellie Sattler",
    description:
      "A paleobotanist in her late 20s to early 30s, Grant's partner both professionally and romantically. Brilliant, assertive, physically brave. She drives the critical Act 2 turning point: volunteering to restore power through the raptor-infested maintenance shed.",
    age: "27-35",
    gender: "Female",
    castingNotes:
      "Must project intelligence AND physical determination — not a secondary love interest but a co-lead. Significant solo action sequences (maintenance shed raptor encounter). Chemistry read with Grant actor is essential. Athletic capability required.",
    actors: emptyActors(),
  },
  {
    id: "jb-ian-malcolm",
    name: "Dr. Ian Malcolm",
    description:
      "A chaotician (chaos theory mathematician) in his 40s. Rock-star academic: black leather, tinted glasses, drawling charisma. His chaos theory exposition is the film's philosophical framework. Injured by the T-Rex mid-film and becomes a sardonic wounded commentator.",
    age: "40-50",
    gender: "Male",
    castingNotes:
      "Extremely specific performance requirement: intellectual flamboyance, almost jazz-musician delivery. Must make chaos theory exposition entertaining rather than lecture-like. Physical requirements limited (injured for much of the film) but the flare sequence is critical. Needs actor with strong comedic timing and distinctive physical mannerisms.",
    actors: emptyActors(),
  },
  {
    id: "jb-john-hammond",
    name: "John Hammond",
    description:
      "The elderly billionaire creator of Jurassic Park. A showman, dreamer, and grandfather figure. Not a villain — a visionary whose optimism blinds him to danger. His arc is from childlike enthusiasm to devastated acceptance that his dream has become a nightmare.",
    age: "70-80",
    gender: "Male",
    castingNotes:
      "Must be grandfatherly, warm, and charismatic enough that the audience initially shares his wonder — then heartbreaking when the dream collapses. Not physically demanding but emotional range is critical. The ice cream scene with Ellie is the film's emotional climax for this character. British or Scottish accent preferred (showman quality).",
    actors: emptyActors(),
  },
  {
    id: "jb-tim-murphy",
    name: "Tim Murphy",
    description:
      "Hammond's grandson, approximately 9-10 years old. A dinosaur-obsessed boy who hero-worships Grant. He is the primary child in peril throughout the film: T-Rex attack, tree fall, stampede, electric fence electrocution, and raptor kitchen chase.",
    age: "9-12",
    gender: "Male",
    castingNotes:
      "Extraordinary child actor required. Must carry extended sequences of genuine terror while remaining sympathetic. Key challenge: the electric fence electrocution and CPR scene is an extended physical/emotional sequence. Must have natural chemistry with Grant actor. Dinosaur enthusiasm must read as authentic, not precocious.",
    actors: emptyActors(),
  },
  {
    id: "jb-lex-murphy",
    name: "Lex Murphy",
    description:
      "Hammond's granddaughter, approximately 12-13 years old. A computer-literate teenager. Her Unix knowledge provides the critical plot resolution (restoring door locks). She is resourceful under extreme pressure.",
    age: "11-14",
    gender: "Female",
    castingNotes:
      "Must credibly portray both teenage vulnerability and technical competence. The 'It's a Unix system!' moment must land as genuine rather than absurd. Significant physical demands in the kitchen raptor sequence. Chemistry with Tim actor essential — must read as genuine siblings.",
    actors: emptyActors(),
  },
  {
    id: "jb-dennis-nedry",
    name: "Dennis Nedry",
    description:
      "Jurassic Park's chief programmer. Overweight, resentful, greedy. He is the human antagonist who disables park security systems to steal embryos. His death by Dilophosaurus is both horrific and darkly comic.",
    age: "35-50",
    gender: "Male",
    castingNotes:
      "Comedic actor who can play genuine menace underneath the buffoonery. Physical comedy required for Dilophosaurus death sequence. Must be able to make technical dialogue (computer commands, system descriptions) feel natural. Solo scenes in the rain require strong screen presence without scene partners.",
    actors: emptyActors(),
  },
  {
    id: "jb-ray-arnold",
    name: "Ray Arnold",
    description:
      "Jurassic Park's chief engineer. A chain-smoking, world-weary systems operator who sees every failure coming. His 'Hold on to your butts' line is iconic. Disappears into the maintenance shed and is found only as a severed arm.",
    age: "35-55",
    gender: "Male",
    castingNotes:
      "Must convey technical competence and exhausted frustration with a dry wit. Chain-smoking is a constant character trait — actor must be comfortable with prop cigarettes across multiple scenes and takes. Relatively limited screen time but every scene must land. Disappears midway through Act 3 — the severed arm reveal is more effective if the audience has connected with the character.",
    actors: emptyActors(),
  },
  {
    id: "jb-robert-muldoon",
    name: "Robert Muldoon",
    description:
      "Jurassic Park's game warden. A seasoned big-game hunter, the only person who truly understands how dangerous the raptors are. Professional, terse, lethal competence. His death — 'Clever girl' — is the film's most famous single-line character moment.",
    age: "40-55",
    gender: "Male",
    castingNotes:
      "Must project absolute physical authority and quiet menace. The 'Clever girl' death scene must play as respect, not defeat. Accent options: Australian, South African, or British (colonial game warden archetype). Weapons handling must look completely natural. Relatively few lines — most of the performance is physical presence and watchfulness.",
    actors: emptyActors(),
  },
  {
    id: "jb-donald-gennaro",
    name: "Donald Gennaro",
    description:
      "The lawyer representing Hammond's investors. Nervous, greedy, cowardly. He abandons the children during the T-Rex attack to hide in a toilet stall, where the T-Rex eats him. His death is played for dark comedy.",
    age: "35-50",
    gender: "Male",
    castingNotes:
      "Comic actor with strong physical comedy chops. The toilet death scene requires precise timing and willingness to play absolute cowardice. Must be dislikeable enough that his death satisfies the audience but human enough that it is still shocking. The abandoning-the-children moment must read as reflexive panic, not calculated evil.",
    actors: emptyActors(),
  },
  {
    id: "jb-henry-wu",
    name: "Dr. Henry Wu",
    description:
      "Jurassic Park's chief geneticist. Appears briefly in the genetics lab / hatchery scene. Calm, professional, explains the cloning process and frog DNA. A relatively small role in this film but a significant franchise character.",
    age: "30-45",
    gender: "Male",
    castingNotes:
      "Must deliver technical genetic exposition naturally and with quiet pride. Limited screen time — one major scene in the hatchery. Asian-American actor preferred (original character). The character must feel like he is a real scientist, not a plot-exposition device.",
    actors: emptyActors(),
  },
  {
    id: "jb-lewis-dodgson",
    name: "Lewis Dodgson",
    description:
      "Head of rival genetics company Biosyn. Appears in one scene: the diner meeting with Nedry where the embryo-theft plan is set. 'Dodgson! We've got Dodgson here!' He provides the modified Barbasol can.",
    age: "35-50",
    gender: "Male",
    castingNotes:
      "One scene only but must establish corporate villain menace efficiently. The diner scene plays as a spy-thriller beat within a dinosaur movie — must feel tonally distinct. Must have strong scene-partner chemistry with Nedry actor.",
    actors: emptyActors(),
  },
  {
    id: "jb-mr-dna",
    name: "Mr. DNA",
    description:
      "Animated character who appears on the park's tour video. A cartoon DNA strand who explains dinosaur cloning to visitors. Voice-only role; character is animated.",
    age: "N/A",
    gender: "N/A",
    castingNotes:
      "Voice casting only. Friendly, educational, slightly cheesy — like a theme-park educational film narrator. Must be clear and engaging enough to make complex genetics accessible to the audience without talking down to them. Southern US or mid-Atlantic accent preferred for folksy charm.",
    actors: emptyActors(),
  },
  {
    id: "jb-helicopter-pilot",
    name: "Helicopter Pilot",
    description:
      "Flies Hammond's helicopter to and from Isla Nublar. A minor role providing transport at the beginning and end of the film.",
    age: "30-50",
    gender: "Any",
    castingNotes:
      "Minimal dialogue. Must look comfortable in a helicopter cockpit. Bookend role: first and last scenes on the island.",
    actors: emptyActors(),
  },
]

/* ------------------------------------------------------------------ */
/*  Locations (from locations.json, cross-ref scenes.json)             */
/* ------------------------------------------------------------------ */
const locations = [
  {
    id: "jb-isla-nublar",
    code: "LOC-001",
    name: "Isla Nublar (Main Island)",
    locationType: "on-location" as const,
    status: "scouted" as const,
    lat: 9.17,
    lng: -83.85,
    address: "Isla Nublar, 120 miles west of Costa Rica",
    vibeTags: ["Tropical", "Volcanic", "Isolated", "Lush"],
    media: [],
    notes: "The fictional island 120 miles west of Costa Rica. All exterior jungle, paddock perimeter, and road sequences take place on the island. Kauai, Hawaii used as primary location double in the original production.",
    dailyRate: "",
    overtimeRate: "",
    securityDeposit: "",
    sceneTags: [
      { sceneNumber: "001", sceneTitle: "Raptor Transfer — Opening Kill" },
      { sceneNumber: "009", sceneTitle: "Helicopter Arrival at Isla Nublar" },
      { sceneNumber: "010", sceneTitle: "Jeep Ride — First Dinosaur Sighting (Brachiosaur)" },
    ],
    scheduleBlocks: [],
    blackoutDates: [],
    bookedTo: null,
  },
  {
    id: "jb-badlands-dig-site",
    code: "LOC-002",
    name: "Badlands Dig Site",
    locationType: "on-location" as const,
    status: "scouted" as const,
    lat: 43.75,
    lng: -101.95,
    address: "Montana / South Dakota Badlands",
    vibeTags: ["Arid", "Desert", "Academic", "Dusty"],
    media: [],
    notes: "Montana badlands where Grant and Sattler excavate Velociraptor fossils. Establishes Grant's character and introduces the 'raptor claw' speech. Must be visually distinct from all island locations.",
    dailyRate: "",
    overtimeRate: "",
    securityDeposit: "",
    sceneTags: [
      { sceneNumber: "002", sceneTitle: "Grant Dig Site — Raptor Claw Speech" },
    ],
    scheduleBlocks: [],
    blackoutDates: [],
    bookedTo: null,
  },
  {
    id: "jb-san-jose-diner",
    code: "LOC-003",
    name: "San Jose Diner",
    locationType: "on-location" as const,
    status: "scouted" as const,
    lat: 9.93,
    lng: -84.08,
    address: "San Jose, Costa Rica",
    vibeTags: ["Urban", "Seedy", "Conspiratorial"],
    media: [],
    notes: "Costa Rican diner where Nedry meets Dodgson. The Barbasol can embryo-smuggling device is introduced. Brief scene but establishes the human threat.",
    dailyRate: "",
    overtimeRate: "",
    securityDeposit: "",
    sceneTags: [
      { sceneNumber: "005", sceneTitle: "Nedry-Dodgson Meeting — Barbasol Can" },
    ],
    scheduleBlocks: [],
    blackoutDates: [],
    bookedTo: null,
  },
  {
    id: "jb-amber-mine",
    code: "LOC-004",
    name: "Amber Mine (Dominican Republic)",
    locationType: "on-location" as const,
    status: "scouted" as const,
    lat: 19.45,
    lng: -70.7,
    address: "Dominican Republic amber mine",
    vibeTags: ["Subterranean", "Amber", "Prehistoric"],
    media: [],
    notes: "Dominican Republic amber mine. Appears in the opening sequence establishing the source of dinosaur DNA. Brief location shoot.",
    dailyRate: "",
    overtimeRate: "",
    securityDeposit: "",
    sceneTags: [],
    scheduleBlocks: [],
    blackoutDates: [],
    bookedTo: null,
  },
  {
    id: "jb-helipad",
    code: "LOC-005",
    name: "Helipad / Waterfall Approach",
    locationType: "on-location" as const,
    status: "scouted" as const,
    lat: 9.17,
    lng: -83.85,
    address: "Isla Nublar helipad, near waterfall",
    vibeTags: ["Dramatic", "Arrival", "Scenic"],
    media: [],
    notes: "Helicopter landing pad on Isla Nublar with dramatic waterfall approach. First visual impression of the island.",
    dailyRate: "",
    overtimeRate: "",
    securityDeposit: "",
    sceneTags: [
      { sceneNumber: "009", sceneTitle: "Helicopter Arrival at Isla Nublar" },
    ],
    scheduleBlocks: [],
    blackoutDates: [],
    bookedTo: null,
  },
  {
    id: "jb-raptor-pen",
    code: "LOC-006",
    name: "Raptor Holding Pen",
    locationType: "studio" as const,
    status: "scouted" as const,
    lat: 0,
    lng: 0,
    address: "Stage build",
    vibeTags: ["Industrial", "Dangerous", "Tense"],
    media: [],
    notes: "Heavy-duty containment pen with crane-fed cow system. Opening sequence: raptor transfer from container to pen goes wrong — the gatekeeper is pulled in. Established as the most dangerous location on the island.",
    dailyRate: "",
    overtimeRate: "",
    securityDeposit: "",
    sceneTags: [
      { sceneNumber: "001", sceneTitle: "Raptor Transfer — Opening Kill" },
    ],
    scheduleBlocks: [],
    blackoutDates: [],
    bookedTo: null,
  },
  {
    id: "jb-genetics-lab",
    code: "LOC-007",
    name: "Genetics Lab / Hatchery",
    locationType: "studio" as const,
    status: "scouted" as const,
    lat: 0,
    lng: 0,
    address: "Stage build — Visitor's Center interior",
    vibeTags: ["Sterile", "Scientific", "Wonder"],
    media: [],
    notes: "Clean-room genetics laboratory with dinosaur egg hatchery. Dr. Wu explains cloning. Baby raptor hatching is key animatronic/practical effect moment.",
    dailyRate: "",
    overtimeRate: "",
    securityDeposit: "",
    sceneTags: [
      { sceneNumber: "012", sceneTitle: "Genetics Lab Tour — Raptor Hatching" },
    ],
    scheduleBlocks: [],
    blackoutDates: [],
    bookedTo: null,
  },
  {
    id: "jb-dining-room",
    code: "LOC-008",
    name: "Visitor's Center Dining Room",
    locationType: "studio" as const,
    status: "scouted" as const,
    lat: 0,
    lng: 0,
    address: "Stage build — Visitor's Center interior",
    vibeTags: ["Corporate", "Debate", "Tension"],
    media: [],
    notes: "Where the group has the 'Could you try to show a little respect?' lunch debate. Hammond's optimism vs. Malcolm's warnings. Chilean sea bass.",
    dailyRate: "",
    overtimeRate: "",
    securityDeposit: "",
    sceneTags: [
      { sceneNumber: "015", sceneTitle: "Lunch Debate — Ethics of Dinosaur Cloning" },
    ],
    scheduleBlocks: [],
    blackoutDates: [],
    bookedTo: null,
  },
  {
    id: "jb-trex-paddock",
    code: "LOC-009",
    name: "T-Rex Paddock / Road",
    locationType: "on-location" as const,
    status: "scouted" as const,
    lat: 9.17,
    lng: -83.85,
    address: "Isla Nublar — main tour road, T-Rex paddock perimeter",
    vibeTags: ["Terrifying", "Iconic", "Night", "Rain"],
    media: [],
    notes: "The T-Rex breakout location. Road with two Ford Explorers stopped at the paddock fence. Must accommodate: rain effects, full-scale animatronic T-Rex, practical fence destruction, Explorer flip, and the 'Must go faster' jeep chase. The most complex shooting location in the film.",
    dailyRate: "",
    overtimeRate: "",
    securityDeposit: "",
    sceneTags: [
      { sceneNumber: "049", sceneTitle: "T-Rex Breakout — Gennaro Death" },
      { sceneNumber: "055", sceneTitle: "T-Rex Flips Explorer with Tim Inside" },
      { sceneNumber: "058", sceneTitle: "T-Rex Chases Jeep — 'Must Go Faster'" },
    ],
    scheduleBlocks: [],
    blackoutDates: [],
    bookedTo: null,
  },
  {
    id: "jb-control-room",
    code: "LOC-010",
    name: "Control Room",
    locationType: "studio" as const,
    status: "scouted" as const,
    lat: 0,
    lng: 0,
    address: "Stage build — Visitor's Center interior",
    vibeTags: ["Tech", "Tense", "Command Center"],
    media: [],
    notes: "Nerve center of Jurassic Park. Multiple practical computer terminals required (Nedry's hack, Arnold's systems, Lex's Unix sequence). 'Ah ah ah, you didn't say the magic word' sequence. Must feel like a real operational facility.",
    dailyRate: "",
    overtimeRate: "",
    securityDeposit: "",
    sceneTags: [
      { sceneNumber: "032", sceneTitle: "Nedry Initiates System Shutdown / Embryo Theft" },
      { sceneNumber: "049", sceneTitle: "T-Rex Breakout — Gennaro Death" },
      { sceneNumber: "098", sceneTitle: "Arnold 'Hold On to Your Butts' — System Reboot" },
      { sceneNumber: "130", sceneTitle: "Lex Hacks Unix System — Door Locks Restored" },
    ],
    scheduleBlocks: [],
    blackoutDates: [],
    bookedTo: null,
  },
  {
    id: "jb-treetop",
    code: "LOC-011",
    name: "Treetop (Brachiosaur Encounter)",
    locationType: "on-location" as const,
    status: "scouted" as const,
    lat: 9.17,
    lng: -83.85,
    address: "Isla Nublar — tall tree near Brachiosaur paddock",
    vibeTags: ["Wonder", "Height", "Gentle", "Night"],
    media: [],
    notes: "Grant and the children spend the night in a tall tree. A Brachiosaur feeds from branches beside them — Tim feeds it. Gentle sequence contrasting with the T-Rex terror that preceded it.",
    dailyRate: "",
    overtimeRate: "",
    securityDeposit: "",
    sceneTags: [
      { sceneNumber: "065", sceneTitle: "Treetop Night — Brachiosaur Feeding" },
    ],
    scheduleBlocks: [],
    blackoutDates: [],
    bookedTo: null,
  },
  {
    id: "jb-gallimimus-field",
    code: "LOC-012",
    name: "Gallimimus Flocking Field",
    locationType: "on-location" as const,
    status: "scouted" as const,
    lat: 9.17,
    lng: -83.85,
    address: "Isla Nublar — open grassland",
    vibeTags: ["Open", "Stampede", "Wonder", "Danger"],
    media: [],
    notes: "Open grassland where the Gallimimus herd stampedes past Grant, Tim, and Lex. The T-Rex picks off a straggler. 'They're flocking this way!'",
    dailyRate: "",
    overtimeRate: "",
    securityDeposit: "",
    sceneTags: [
      { sceneNumber: "075", sceneTitle: "Gallimimus Stampede — T-Rex Kills Straggler" },
    ],
    scheduleBlocks: [],
    blackoutDates: [],
    bookedTo: null,
  },
  {
    id: "jb-perimeter-fence",
    code: "LOC-013",
    name: "Perimeter Fence",
    locationType: "on-location" as const,
    status: "scouted" as const,
    lat: 9.17,
    lng: -83.85,
    address: "Isla Nublar — electrified perimeter fence section",
    vibeTags: ["Danger", "Electricity", "Height", "Tension"],
    media: [],
    notes: "Electrified perimeter fence. Tim is climbing when power is restored — electrocution, fall, and CPR sequence. Practical SFX required. Child actor safety is paramount.",
    dailyRate: "",
    overtimeRate: "",
    securityDeposit: "",
    sceneTags: [
      { sceneNumber: "106b", sceneTitle: "Tim Electrocuted on Fence — Grant CPR" },
    ],
    scheduleBlocks: [],
    blackoutDates: [],
    bookedTo: null,
  },
  {
    id: "jb-maintenance-shed",
    code: "LOC-014",
    name: "Maintenance Shed",
    locationType: "studio" as const,
    status: "scouted" as const,
    lat: 0,
    lng: 0,
    address: "Stage build",
    vibeTags: ["Claustrophobic", "Dark", "Industrial", "Horror"],
    media: [],
    notes: "Underground maintenance facility with maze of pipes and electrical systems. Ellie restores power via breaker panel (fluorescent lights activate in sequence). Arnold's severed arm discovery. Raptor attack. Must be dark, claustrophobic, and genuinely terrifying.",
    dailyRate: "",
    overtimeRate: "",
    securityDeposit: "",
    sceneTags: [
      { sceneNumber: "106b", sceneTitle: "Ellie Restores Power — Arnold Arm / Raptor Attack" },
    ],
    scheduleBlocks: [],
    blackoutDates: [],
    bookedTo: null,
  },
  {
    id: "jb-vc-kitchen",
    code: "LOC-015",
    name: "Visitor's Center Kitchen",
    locationType: "studio" as const,
    status: "scouted" as const,
    lat: 0,
    lng: 0,
    address: "Stage build — Visitor's Center interior",
    vibeTags: ["Stainless Steel", "Horror", "Chase", "Reflections"],
    media: [],
    notes: "Commercial kitchen designed from the outset for raptor chase choreography. Shiny stainless steel for raptor reflection/confusion gag. Walk-in freezer with pin-locking handle (Tim's raptor trap). Overhead door mechanism (gets stuck on Lex). Animatronic raptor integration points throughout.",
    dailyRate: "",
    overtimeRate: "",
    securityDeposit: "",
    sceneTags: [
      { sceneNumber: "124", sceneTitle: "Raptor Kitchen Chase — Tim Freezer Trap" },
    ],
    scheduleBlocks: [],
    blackoutDates: [],
    bookedTo: null,
  },
  {
    id: "jb-vc-lobby-rotunda",
    code: "LOC-016",
    name: "Visitor's Center Lobby / Rotunda",
    locationType: "studio" as const,
    status: "scouted" as const,
    lat: 0,
    lng: 0,
    address: "Stage build — Visitor's Center interior",
    vibeTags: ["Grand", "Climax", "Skeleton", "Iconic"],
    media: [],
    notes: "Grand rotunda with full-scale Brachiosaur skeleton display. The film's climactic location: raptors corner the group on the skeleton scaffolding, then the T-Rex enters and kills both raptors. 'When Dinosaurs Ruled the Earth' banner falls. Skeleton scaffolding must support actor weight and have rigged collapse points.",
    dailyRate: "",
    overtimeRate: "",
    securityDeposit: "",
    sceneTags: [
      { sceneNumber: "130", sceneTitle: "Lex Hacks Unix System — Door Locks Restored" },
      { sceneNumber: "137", sceneTitle: "T-Rex Enters Rotunda, Kills Raptors — Escape" },
    ],
    scheduleBlocks: [],
    blackoutDates: [],
    bookedTo: null,
  },
  {
    id: "jb-nedry-road-dock",
    code: "LOC-017",
    name: "East Dock Road (Nedry's Route)",
    locationType: "on-location" as const,
    status: "scouted" as const,
    lat: 9.17,
    lng: -83.85,
    address: "Isla Nublar — road to east dock",
    vibeTags: ["Rain", "Night", "Isolation", "Horror"],
    media: [],
    notes: "Muddy jungle road in torrential rain. Nedry's Jeep gets stuck. He encounters the Dilophosaurus at the winch point. Frill display, venom spit, Jeep death. Must be extremely dark and rainy.",
    dailyRate: "",
    overtimeRate: "",
    securityDeposit: "",
    sceneTags: [
      { sceneNumber: "049", sceneTitle: "Nedry — Dilophosaurus Encounter and Death" },
    ],
    scheduleBlocks: [],
    blackoutDates: [],
    bookedTo: null,
  },
  {
    id: "jb-sick-triceratops-field",
    code: "LOC-018",
    name: "Sick Triceratops Field",
    locationType: "on-location" as const,
    status: "scouted" as const,
    lat: 9.17,
    lng: -83.85,
    address: "Isla Nublar — open paddock",
    vibeTags: ["Gentle", "Wonder", "Veterinary"],
    media: [],
    notes: "Open field where the group encounters the sick Triceratops. Ellie investigates the illness (West Indian Lilac berries). First physical contact between humans and dinosaurs. Full-scale practical Triceratops.",
    dailyRate: "",
    overtimeRate: "",
    securityDeposit: "",
    sceneTags: [
      { sceneNumber: "022", sceneTitle: "Sick Triceratops — Ellie Investigates" },
    ],
    scheduleBlocks: [],
    blackoutDates: [],
    bookedTo: null,
  },
  {
    id: "jb-ford-explorer-tour-vehicles",
    code: "LOC-019",
    name: "Ford Explorer Tour Vehicles (Interior)",
    locationType: "studio" as const,
    status: "scouted" as const,
    lat: 0,
    lng: 0,
    address: "Stage build — vehicle interiors",
    vibeTags: ["Confined", "Terror", "Iconic"],
    media: [],
    notes: "Interior of the automated Ford Explorer tour vehicles. Key scenes: water glass vibration, T-Rex attack from inside, flashlight attraction, sunroof push-through. Vehicle must be built for interior shooting with removable panels.",
    dailyRate: "",
    overtimeRate: "",
    securityDeposit: "",
    sceneTags: [
      { sceneNumber: "049", sceneTitle: "T-Rex Breakout — Explorer Interior" },
      { sceneNumber: "055", sceneTitle: "T-Rex Flips Explorer with Tim Inside" },
    ],
    scheduleBlocks: [],
    blackoutDates: [],
    bookedTo: null,
  },
  {
    id: "jb-air-duct-crawl-space",
    code: "LOC-020",
    name: "Air Duct / Ceiling Crawl Space",
    locationType: "studio" as const,
    status: "scouted" as const,
    lat: 0,
    lng: 0,
    address: "Stage build — above Visitor's Center",
    vibeTags: ["Claustrophobic", "Escape", "Danger"],
    media: [],
    notes: "Ceiling crawl space / air duct above the Visitor's Center. The group escapes raptors through the ducts. Raptor smashes through ceiling panels — Lex is lifted on its head. Must be designed for raptor animatronic integration from below.",
    dailyRate: "",
    overtimeRate: "",
    securityDeposit: "",
    sceneTags: [
      { sceneNumber: "135", sceneTitle: "Raptor Bursts Through Ceiling Panels / Lex Lifted" },
      { sceneNumber: "136", sceneTitle: "Group Crawls Through Air Duct" },
    ],
    scheduleBlocks: [],
    blackoutDates: [],
    bookedTo: null,
  },
]

/* ------------------------------------------------------------------ */
/*  Props (from props.json)                                            */
/* ------------------------------------------------------------------ */
const props = [
  {
    id: "jb-barbasol-can",
    name: "Modified Barbasol Can (Embryo Carrier)",
    model: "Barbasol shaving cream can — modified",
    category: "Hero Prop",
    brand: "Barbasol",
    serialNumber: "",
    skuBarcode: "",
    notes: "Custom coolant chamber inside a Barbasol shaving cream can. Holds 15 dinosaur embryo vials. Timer-limited coolant (Nedry has 24 hours). Must look like a normal shaving cream can when closed, reveal embryo chamber when opened. Functional opening mechanism required for close-up.",
    imageUrl: "",
    purchaseType: "fabrication",
    unitPrice: "",
    quantity: 3,
    bookedTo: null,
    votes: [],
    comments: [],
    availability: [],
    status: "available" as const,
    sceneIds: ["jb-scene-005", "jb-scene-032", "jb-scene-049"],
    characterId: "jb-dennis-nedry",
  },
  {
    id: "jb-raptor-claw-fossil",
    name: "Raptor Claw Fossil",
    model: "Velociraptor foot claw — fossilised replica",
    category: "Hero Prop",
    brand: "",
    serialNumber: "",
    skuBarcode: "",
    notes: "Oversized Velociraptor foot claw. Grant uses it to terrify the disrespectful kid at the dig site. Must be large enough to read on camera, anatomically plausible. Carried by Grant — almost a talisman.",
    imageUrl: "",
    purchaseType: "fabrication",
    unitPrice: "",
    quantity: 2,
    bookedTo: null,
    votes: [],
    comments: [],
    availability: [],
    status: "available" as const,
    sceneIds: ["jb-scene-002"],
    characterId: "jb-alan-grant",
  },
  {
    id: "jb-dino-embryo-vials",
    name: "Dinosaur Embryo Vials",
    model: "Cryo vials with species labels",
    category: "Hero Prop",
    brand: "",
    serialNumber: "",
    skuBarcode: "",
    notes: "Set of 15 cryo vials labeled with dinosaur species names. Fit inside the Barbasol can coolant chamber. Close-up hero props — labeling must be legible on camera.",
    imageUrl: "",
    purchaseType: "fabrication",
    unitPrice: "",
    quantity: 15,
    bookedTo: null,
    votes: [],
    comments: [],
    availability: [],
    status: "available" as const,
    sceneIds: ["jb-scene-032"],
    characterId: "jb-dennis-nedry",
  },
  {
    id: "jb-flare",
    name: "Road Flare",
    model: "Standard road safety flare",
    category: "Action Prop",
    brand: "",
    serialNumber: "",
    skuBarcode: "",
    notes: "Grant uses a lit road flare to lure the T-Rex away from the children. Malcolm then uses one and is chased. Must burn with strong red/pink light, SFX practical flame. Multiple takes = large quantity needed.",
    imageUrl: "",
    purchaseType: "purchase",
    unitPrice: "",
    quantity: 50,
    bookedTo: null,
    votes: [],
    comments: [],
    availability: [],
    status: "available" as const,
    sceneIds: ["jb-scene-049"],
    characterId: "jb-alan-grant",
  },
  {
    id: "jb-water-glass",
    name: "Water Glass (Vibration Effect)",
    model: "Clear glass tumbler",
    category: "Hero Prop",
    brand: "",
    serialNumber: "",
    skuBarcode: "",
    notes: "The iconic water glass that shows concentric ripple rings as the T-Rex approaches. Requires practical vibration rig built into the vehicle dashboard. Must be a specific glass shape that shows ripples clearly.",
    imageUrl: "",
    purchaseType: "purchase",
    unitPrice: "",
    quantity: 12,
    bookedTo: null,
    votes: [],
    comments: [],
    availability: [],
    status: "available" as const,
    sceneIds: ["jb-scene-049"],
  },
  {
    id: "jb-night-vision-goggles",
    name: "Night Vision Goggles",
    model: "Military-style NVGs",
    category: "Hero Prop",
    brand: "",
    serialNumber: "",
    skuBarcode: "",
    notes: "Tim's night vision goggles. Used during the T-Rex approach sequence — Tim sees the T-Rex through them. Must be functional enough to show green-tinted POV on camera.",
    imageUrl: "",
    purchaseType: "purchase",
    unitPrice: "",
    quantity: 3,
    bookedTo: null,
    votes: [],
    comments: [],
    availability: [],
    status: "available" as const,
    sceneIds: ["jb-scene-049"],
    characterId: "jb-tim-murphy",
  },
  {
    id: "jb-spas12-shotgun",
    name: "Franchi SPAS-12 Shotgun",
    model: "SPAS-12 — folding stock",
    category: "Weapon",
    brand: "Franchi",
    serialNumber: "",
    skuBarcode: "",
    notes: "Muldoon's signature weapon. Carried throughout the film. Used in the raptor pen opening sequence and the 'Clever girl' scene. Requires certified armory supervision on all shooting days.",
    imageUrl: "",
    purchaseType: "rental",
    unitPrice: "",
    quantity: 2,
    bookedTo: null,
    votes: [],
    comments: [],
    availability: [],
    status: "available" as const,
    sceneIds: ["jb-scene-001", "jb-scene-106b"],
    characterId: "jb-robert-muldoon",
    requiresArmorySupervision: true,
  },
  {
    id: "jb-amber-cane",
    name: "Hammond's Amber-Topped Cane",
    model: "Walking cane with mosquito-in-amber top",
    category: "Hero Prop",
    brand: "",
    serialNumber: "",
    skuBarcode: "",
    notes: "John Hammond's signature walking cane topped with a large piece of amber containing a prehistoric mosquito. Establishes the DNA-extraction premise visually. Must be elegant, showman-like.",
    imageUrl: "",
    purchaseType: "fabrication",
    unitPrice: "",
    quantity: 3,
    bookedTo: null,
    votes: [],
    comments: [],
    availability: [],
    status: "available" as const,
    sceneIds: ["jb-scene-002", "jb-scene-009", "jb-scene-137"],
    characterId: "jb-john-hammond",
  },
  {
    id: "jb-satellite-phone",
    name: "Satellite Phone",
    model: "Early 1990s satellite phone",
    category: "Practical Prop",
    brand: "",
    serialNumber: "",
    skuBarcode: "",
    notes: "Period-appropriate satellite phone. Used by Hammond to maintain contact with the mainland. 1990s era technology — large, clunky, with antenna.",
    imageUrl: "",
    purchaseType: "purchase",
    unitPrice: "",
    quantity: 2,
    bookedTo: null,
    votes: [],
    comments: [],
    availability: [],
    status: "available" as const,
    sceneIds: [],
    characterId: "jb-john-hammond",
  },
  {
    id: "jb-prop-cigarettes",
    name: "Herbal Prop Cigarettes (Arnold)",
    model: "Herbal cigarettes",
    category: "Consumable Prop",
    brand: "",
    serialNumber: "",
    skuBarcode: "",
    notes: "Ray Arnold is a chain smoker. Herbal cigarettes only — no tobacco. Must light and produce smoke convincingly. Large quantity needed for continuity across multiple scenes and takes. Set ventilation required for interior scenes.",
    imageUrl: "",
    purchaseType: "purchase",
    unitPrice: "",
    quantity: 200,
    bookedTo: null,
    votes: [],
    comments: [],
    availability: [],
    status: "available" as const,
    sceneIds: ["jb-scene-032", "jb-scene-049", "jb-scene-098"],
    characterId: "jb-ray-arnold",
  },
  {
    id: "jb-severed-arm",
    name: "Arnold's Severed Arm Prosthetic",
    model: "Prosthetic severed arm — matched to actor",
    category: "SFX Prop",
    brand: "",
    serialNumber: "",
    skuBarcode: "",
    notes: "Prosthetic severed arm that matches the actor playing Arnold. Must match actor's arm dimensions and costume sleeve precisely. Found by Ellie in the maintenance shed. Manufacturing must begin immediately after Arnold actor is cast.",
    imageUrl: "",
    purchaseType: "fabrication",
    unitPrice: "",
    quantity: 2,
    bookedTo: null,
    votes: [],
    comments: [],
    availability: [],
    status: "available" as const,
    sceneIds: ["jb-scene-106b"],
    characterId: "jb-ray-arnold",
  },
  {
    id: "jb-ford-explorers",
    name: "Ford Explorer Tour Vehicles",
    model: "1992 Ford Explorer XLT — customized",
    category: "Vehicle",
    brand: "Ford",
    serialNumber: "",
    skuBarcode: "",
    notes: "Two custom-painted Ford Explorers on electrified guide rail (automated). Red/green Jurassic Park livery. Interior screens for Mr. DNA tour narration. One must be rigged for T-Rex flip (structural reinforcement). Water glass vibration rig in dashboard.",
    imageUrl: "",
    purchaseType: "purchase",
    unitPrice: "",
    quantity: 4,
    bookedTo: null,
    votes: [],
    comments: [],
    availability: [],
    status: "available" as const,
    sceneIds: ["jb-scene-015", "jb-scene-022", "jb-scene-049", "jb-scene-055"],
  },
  {
    id: "jb-jeep-wrangler",
    name: "Jeep Wrangler (Staff Vehicles)",
    model: "1992 Jeep Wrangler Sahara",
    category: "Vehicle",
    brand: "Jeep",
    serialNumber: "",
    skuBarcode: "",
    notes: "Jurassic Park staff Jeeps — JP livery with number markings. Used in the 'Must go faster' T-Rex chase. Must be capable of high-speed driving on unpaved roads. Multiple units needed.",
    imageUrl: "",
    purchaseType: "purchase",
    unitPrice: "",
    quantity: 4,
    bookedTo: null,
    votes: [],
    comments: [],
    availability: [],
    status: "available" as const,
    sceneIds: ["jb-scene-010", "jb-scene-058"],
  },
  {
    id: "jb-when-dinosaurs-banner",
    name: "'When Dinosaurs Ruled the Earth' Banner",
    model: "Large fabric banner",
    category: "Set Dressing",
    brand: "",
    serialNumber: "",
    skuBarcode: "",
    notes: "Large banner hanging in the Visitor's Center rotunda. Falls dramatically during the T-Rex climax — the film's visual thesis statement. Must be rigged for timed release.",
    imageUrl: "",
    purchaseType: "fabrication",
    unitPrice: "",
    quantity: 3,
    bookedTo: null,
    votes: [],
    comments: [],
    availability: [],
    status: "available" as const,
    sceneIds: ["jb-scene-137"],
  },
  {
    id: "jb-ice-cream",
    name: "Melting Ice Cream (Hammond Scene)",
    model: "Multiple ice cream containers/scoops",
    category: "Food Prop",
    brand: "",
    serialNumber: "",
    skuBarcode: "",
    notes: "Hammond eats melting ice cream alone while the park collapses around him. 'They were all so sure I'd have to get out ... I built this place.' Must look like premium artisan ice cream, progressively melting across takes.",
    imageUrl: "",
    purchaseType: "purchase",
    unitPrice: "",
    quantity: 20,
    bookedTo: null,
    votes: [],
    comments: [],
    availability: [],
    status: "available" as const,
    sceneIds: ["jb-scene-098"],
    characterId: "jb-john-hammond",
  },
  {
    id: "jb-jello",
    name: "Jell-O (Raptor Kitchen Scene)",
    model: "Lime green Jell-O on plate",
    category: "Food Prop",
    brand: "Jell-O",
    serialNumber: "",
    skuBarcode: "",
    notes: "Lex's shaking hand holding a spoon of Jell-O as the raptor enters the kitchen. The wobble of the Jell-O mirrors her terror. Must be the right consistency to wobble visibly on camera.",
    imageUrl: "",
    purchaseType: "purchase",
    unitPrice: "",
    quantity: 30,
    bookedTo: null,
    votes: [],
    comments: [],
    availability: [],
    status: "available" as const,
    sceneIds: ["jb-scene-124"],
    characterId: "jb-lex-murphy",
  },
  {
    id: "jb-computer-terminals",
    name: "Control Room Computer Terminals",
    model: "Silicon Graphics workstations + custom screens",
    category: "Practical Prop",
    brand: "Silicon Graphics",
    serialNumber: "",
    skuBarcode: "",
    notes: "Full array of functional or screen-playback computer terminals. Key sequences: Nedry's 'Whte Rbt.Obj' hack program, Arnold's system monitoring, Lex's IRIX FSN file manager ('It's a Unix system!'). All monitor content must be designed and approved before construction. Nedry's station must be distinctively personal.",
    imageUrl: "",
    purchaseType: "purchase",
    unitPrice: "",
    quantity: 8,
    bookedTo: null,
    votes: [],
    comments: [],
    availability: [],
    status: "available" as const,
    sceneIds: ["jb-scene-032", "jb-scene-049", "jb-scene-130"],
  },
]

/* ------------------------------------------------------------------ */
/*  Costumes (from costumes.json + styling.json)                       */
/* ------------------------------------------------------------------ */
const costumes: any = {
  actorSpecs: {},
  inventory: [
    {
      id: "jb-costume-grant-dig",
      name: "Grant — Dig Site (Blue chambray shirt, khakis, red bandana)",
      type: "costume-piece",
      status: "in-stock",
      size: "",
      imageUrl: "",
      vibeTags: ["Rugged", "Academic", "Desert", "Field Work"],
      notes: "Blue chambray work shirt, belted khaki trousers, worn boots, red kerchief/bandana. Must look genuinely lived-in and dusty. Establishes Grant as a working field scientist. Wide-brimmed hat.",
    },
    {
      id: "jb-costume-grant-island",
      name: "Grant — Island (Blue chambray, khakis + leather belt)",
      type: "costume-piece",
      status: "in-stock",
      imageUrl: "",
      vibeTags: ["Adventure", "Continuity", "Distressed"],
      notes: "Same base costume as dig site but progressively distressed through the film. Mud, rain, sweat. Multiple copies at different distress levels needed for continuity.",
    },
    {
      id: "jb-costume-ellie-dig",
      name: "Sattler — Dig Site (Pink tank top, khaki shorts)",
      type: "costume-piece",
      status: "in-stock",
      imageUrl: "",
      vibeTags: ["Practical", "Feminine", "Academic"],
      notes: "Pink sleeveless top, tied-front chambray overshirt, khaki shorts, work boots. Practical and attractive. Must be able to get dirty.",
    },
    {
      id: "jb-costume-ellie-island",
      name: "Sattler — Island (Pink top, khaki shorts + safari shirt)",
      type: "costume-piece",
      status: "in-stock",
      imageUrl: "",
      vibeTags: ["Action", "Practical", "Distressed"],
      notes: "Same base as dig site with safari/utility shirt added. Progressive distressing. Must allow full range of physical movement for action sequences (maintenance shed, running).",
    },
    {
      id: "jb-costume-malcolm-black",
      name: "Malcolm — All Black Ensemble",
      type: "costume-piece",
      status: "in-stock",
      imageUrl: "",
      vibeTags: ["Rock Star", "Academic", "Black", "Leather"],
      notes: "Head-to-toe black: leather jacket, black shirt (partially unbuttoned), black trousers, black shoes. Tinted sunglasses. The 'rock star mathematician' look. Jacket removed after T-Rex injury — shirt becomes progressively opened/disheveled.",
    },
    {
      id: "jb-costume-hammond-white",
      name: "Hammond — White Linen Suit + Amber Cane",
      type: "costume-piece",
      status: "in-stock",
      imageUrl: "",
      vibeTags: ["Showman", "White", "Tropical", "Grandfather"],
      notes: "White/cream linen suit, Panama-style hat, white shoes. Showman/impresario aesthetic. Must look expensive but approachable. The amber-topped cane is integral to the costume. Suit gets progressively rumpled as the park fails.",
    },
    {
      id: "jb-costume-nedry-hawaiian",
      name: "Nedry — Hawaiian Shirt Ensemble",
      type: "costume-piece",
      status: "in-stock",
      imageUrl: "",
      vibeTags: ["Slobbish", "Colorful", "Rain Gear"],
      notes: "Loud Hawaiian shirt, cargo pants, sneakers. Rain slicker/poncho added for the dock run sequence. Must accommodate Barbasol can concealment. Large sizing to emphasize physical bulk. Progressively drenched.",
    },
    {
      id: "jb-costume-arnold-tech",
      name: "Arnold — Tech Staff Uniform",
      type: "costume-piece",
      status: "in-stock",
      imageUrl: "",
      vibeTags: ["Work Wear", "Corporate", "Cigarette Burns"],
      notes: "JP-branded work shirt or polo, dark trousers, comfortable shoes. Perpetual cigarette. Must match the severed arm prosthetic sleeve precisely. No-nonsense working attire.",
    },
    {
      id: "jb-costume-muldoon-safari",
      name: "Muldoon — Safari/Game Warden Khakis",
      type: "costume-piece",
      status: "in-stock",
      imageUrl: "",
      vibeTags: ["Safari", "Military", "Practical", "Authority"],
      notes: "Khaki safari shorts, short-sleeve button-up, knee socks, boots. Wide-brimmed hat and sunglasses. Classic game warden look with military precision. Must accommodate shotgun holster/carry.",
    },
    {
      id: "jb-costume-gennaro-suit",
      name: "Gennaro — Business Suit",
      type: "costume-piece",
      status: "in-stock",
      imageUrl: "",
      vibeTags: ["Corporate", "Overdressed", "Lawyer"],
      notes: "Business suit — overdressed for a tropical island. Tie loosened as things go wrong. The suit visually establishes him as the one person who doesn't belong on the island. Must be destructible for the T-Rex toilet scene.",
    },
    {
      id: "jb-costume-wu-labcoat",
      name: "Wu — Lab Coat + Business Casual",
      type: "costume-piece",
      status: "in-stock",
      imageUrl: "",
      vibeTags: ["Sterile", "Scientific", "Professional"],
      notes: "White lab coat over business casual attire. Clean, professional, slightly corporate-scientific. Must contrast with the field-worn looks of the visitors.",
    },
    {
      id: "jb-costume-tim-casual",
      name: "Tim — Kid Casual (Dinosaur T-shirt)",
      type: "costume-piece",
      status: "in-stock",
      imageUrl: "",
      vibeTags: ["Kid", "Dinosaur Fan", "Distressed"],
      notes: "Dinosaur-themed t-shirt, cargo shorts or jeans, sneakers. Kid who loves dinosaurs — must read immediately as a dino-nerd. Progressively destroyed through the film. Multiple copies at different distress levels.",
    },
    {
      id: "jb-costume-lex-sporty",
      name: "Lex — Sporty Teen (Baseball cap, jersey)",
      type: "costume-piece",
      status: "in-stock",
      imageUrl: "",
      vibeTags: ["Sporty", "Teen", "Practical"],
      notes: "Baseball cap, sporty jersey or t-shirt, practical pants. Active, tomboyish. Must allow full physical range for kitchen chase and climbing sequences. Progressively distressed.",
    },
  ],
  looks: [
    {
      id: "look-grant-dig",
      name: "Grant — Badlands Dig Site",
      characterId: "jb-alan-grant",
      changeNumber: "Change 1",
      scriptDays: ["Day 1"],
      sceneNumbers: ["Sc 2"],
      itemIds: ["jb-costume-grant-dig"],
      continuityNotes: "Dusty, sun-worn. Red bandana around neck. Raptor claw fossil in hand/pocket.",
      referencePhotos: [],
      matchPhotos: [],
    },
    {
      id: "look-grant-island",
      name: "Grant — Island (Full Film)",
      characterId: "jb-alan-grant",
      changeNumber: "Change 2",
      scriptDays: ["Day 2", "Day 3", "Day 4"],
      sceneNumbers: ["Sc 9", "Sc 10", "Sc 12", "Sc 15", "Sc 22", "Sc 49", "Sc 55", "Sc 58", "Sc 65", "Sc 75", "Sc 106b", "Sc 124", "Sc 130", "Sc 137"],
      itemIds: ["jb-costume-grant-island"],
      continuityNotes: "Progressive distress: clean at arrival → mud/rain after T-Rex → torn and filthy by finale. Sleeves rolled up after Act 1.",
      referencePhotos: [],
      matchPhotos: [],
    },
    {
      id: "look-ellie-dig",
      name: "Sattler — Badlands Dig Site",
      characterId: "jb-ellie-sattler",
      changeNumber: "Change 1",
      scriptDays: ["Day 1"],
      sceneNumbers: ["Sc 2"],
      itemIds: ["jb-costume-ellie-dig"],
      continuityNotes: "Dirty hands, sun-kissed. Hair up in practical ponytail.",
      referencePhotos: [],
      matchPhotos: [],
    },
    {
      id: "look-ellie-island",
      name: "Sattler — Island (Full Film)",
      characterId: "jb-ellie-sattler",
      changeNumber: "Change 2",
      scriptDays: ["Day 2", "Day 3", "Day 4"],
      sceneNumbers: ["Sc 9", "Sc 10", "Sc 12", "Sc 15", "Sc 22", "Sc 106b", "Sc 130", "Sc 137"],
      itemIds: ["jb-costume-ellie-island"],
      continuityNotes: "Safari shirt tied at waist initially, then worn open. Sleeves rolled. Mud and blood (Arnold's arm) from maintenance shed onwards.",
      referencePhotos: [],
      matchPhotos: [],
    },
    {
      id: "look-malcolm-all",
      name: "Malcolm — All Black (Full Film)",
      characterId: "jb-ian-malcolm",
      changeNumber: "Change 1",
      scriptDays: ["Day 2", "Day 3", "Day 4"],
      sceneNumbers: ["Sc 9", "Sc 10", "Sc 15", "Sc 49", "Sc 58", "Sc 098", "Sc 137"],
      itemIds: ["jb-costume-malcolm-black"],
      continuityNotes: "Leather jacket ON for arrival through lunch. Jacket OFF after T-Rex injury — shirt open, tourniquet/bandage visible. Increasingly pale and disheveled.",
      referencePhotos: [],
      matchPhotos: [],
    },
    {
      id: "look-hammond-all",
      name: "Hammond — White Suit (Full Film)",
      characterId: "jb-john-hammond",
      changeNumber: "Change 1",
      scriptDays: ["Day 2", "Day 3", "Day 4"],
      sceneNumbers: ["Sc 2", "Sc 9", "Sc 10", "Sc 12", "Sc 15", "Sc 098", "Sc 137"],
      itemIds: ["jb-costume-hammond-white"],
      continuityNotes: "Pristine white suit on arrival. Progressively rumpled and stained. Jacket off, collar loose for ice cream scene. Hat removed after Act 1.",
      referencePhotos: [],
      matchPhotos: [],
    },
    {
      id: "look-nedry-all",
      name: "Nedry — Hawaiian + Rain Gear",
      characterId: "jb-dennis-nedry",
      changeNumber: "Change 1",
      scriptDays: ["Day 2", "Day 3"],
      sceneNumbers: ["Sc 5", "Sc 32", "Sc 49"],
      itemIds: ["jb-costume-nedry-hawaiian"],
      continuityNotes: "Hawaiian shirt indoors. Rain slicker/poncho added for dock run. Barbasol can concealed in jacket/bag. Drenched and mud-covered for Dilophosaurus scene.",
      referencePhotos: [],
      matchPhotos: [],
    },
    {
      id: "look-muldoon-all",
      name: "Muldoon — Game Warden (Full Film)",
      characterId: "jb-robert-muldoon",
      changeNumber: "Change 1",
      scriptDays: ["Day 2", "Day 3", "Day 4"],
      sceneNumbers: ["Sc 1", "Sc 106b"],
      itemIds: ["jb-costume-muldoon-safari"],
      continuityNotes: "Always immaculate military precision. Shotgun always present. Hat and sunglasses on for exterior, off for interior. Khaki shorts, knee socks maintained throughout.",
      referencePhotos: [],
      matchPhotos: [],
    },
  ],
  shoppingList: [],
}

/* ------------------------------------------------------------------ */
/*  Full CastingState export                                           */
/* ------------------------------------------------------------------ */
export const jurassicAIData: CastingState = {
  projects: [
    {
      id: "proj_jurassic_ai",
      name: "Jurassic Park (1993) — Script Breakdown",
      description: "Complete pre-production breakdown of Jurassic Park (1993) based on screenplay analysis. 14 characters, 20 locations, 17 props, and full costume/look inventory derived from scene-by-scene script data.",
      characters,
      createdDate: Date.now() - 30 * 24 * 60 * 60 * 1000,
      modifiedDate: Date.now(),
      props,
      locations,
      costumes,
    } as any,
  ],
  users: [
    {
      id: "userDS",
      name: "Director Spielberg",
      initials: "DS",
      email: "spielberg@example.com",
      role: "Director",
      color: "#1d4ed8",
      bgColor: "#dbeafe",
    },
    {
      id: "userCR",
      name: "Casting Robot",
      initials: "CR",
      email: "casting@example.com",
      role: "Casting Director",
      color: "#5b21b6",
      bgColor: "#ede9fe",
    },
    {
      id: "userPV",
      name: "Producer Vance",
      initials: "PV",
      email: "producer@example.com",
      role: "Producer",
      color: "#be185d",
      bgColor: "#fce7f3",
    },
  ],
  currentUser: null,
  cardViewSettings: {
    age: true,
    playingAge: true,
    agent: true,
    location: true,
    imdbUrl: true,
    skills: true,
    notes: true,
    status: true,
    showVotes: true,
    showActionButtons: true,
  } as any,
  currentFocus: {
    currentProjectId: "proj_jurassic_ai",
    characterId: "jb-alan-grant",
    activeTabKey: "longList",
    cardDisplayMode: "detailed",
    currentSortOption: "alphabetical",
    searchTerm: "",
    searchTags: [],
    savedSearches: [],
    playerView: {
      isOpen: false,
      currentIndex: 0,
      currentHeadshotIndex: 0,
    },
  } as any,
  tabDefinitions: [
    { key: "longList", name: "Long List", isCustom: false },
    { key: "shortLists", name: "Shortlist", isCustom: false },
    { key: "audition", name: "Audition", isCustom: false },
    { key: "approval", name: "Approval", isCustom: false },
  ],
  sortOptionDefinitions: [
    { key: "alphabetical", label: "Alphabetical (A-Z)" },
    { key: "consensus", label: "By Consensus" },
    { key: "status", label: "By Status" },
  ],
  predefinedStatuses,
  notifications: [],
  permissionLevels: [
    { id: "admin", label: "Producer", description: "Full access to all features, can manage users and settings." },
    { id: "casting_director", label: "Casting Director", description: "Can manage actors, auditions, and make casting decisions." },
    { id: "producer", label: "Director", description: "Can view all data and approve final casting decisions." },
    { id: "viewer", label: "Viewer", description: "Read-only access to casting data." },
  ],
  modals: {},
  terminology: { actor: { singular: "Actor", plural: "Actors" }, character: { singular: "Character", plural: "Characters" } },
  tabDisplayNames: {},
  scheduleEntries: [],
  productionPhases: [],
  scenes: [],
  tabNotifications: {},
}
