// lib/mockData.ts

import type { CastingState } from "@/types/casting"

const predefinedStatuses = [
  {
    id: "new",
    label: "New",
    bgColor: "bg-gray-200",
    textColor: "text-gray-700",
    category: "application",
    priority: 1,
    isCustom: false,
  },
  {
    id: "applied",
    label: "Applied",
    bgColor: "bg-blue-200",
    textColor: "text-blue-700",
    category: "application",
    priority: 2,
    isCustom: false,
  },
  {
    id: "interviewing",
    label: "Interviewing",
    bgColor: "bg-purple-200",
    textColor: "text-purple-700",
    category: "application",
    priority: 3,
    isCustom: false,
  },
  {
    id: "offer",
    label: "Offer",
    bgColor: "bg-green-200",
    textColor: "text-green-700",
    category: "application",
    priority: 4,
    isCustom: false,
  },
  {
    id: "rejected",
    label: "Rejected",
    bgColor: "bg-red-200",
    textColor: "text-red-700",
    category: "application",
    priority: 5,
    isCustom: false,
  },
  {
    id: "closed",
    label: "Closed",
    bgColor: "bg-gray-400",
    textColor: "text-gray-900",
    category: "application",
    priority: 6,
    isCustom: false,
  },
  // Contact Status Categories
  {
    id: "contact-audition",
    label: "Audition Invited",
    bgColor: "bg-blue-100",
    textColor: "text-blue-800",
    category: "contact",
    priority: 1,
    isCustom: false,
  },
  {
    id: "contact-callback",
    label: "Callback Invited",
    bgColor: "bg-green-100",
    textColor: "text-green-800",
    category: "contact",
    priority: 2,
    isCustom: false,
  },
  {
    id: "contact-rejection",
    label: "Thanked",
    bgColor: "bg-gray-100",
    textColor: "text-gray-800",
    category: "contact",
    priority: 3,
    isCustom: false,
  },
  {
    id: "contact-offer",
    label: "Offer Sent",
    bgColor: "bg-purple-100",
    textColor: "text-purple-800",
    category: "contact",
    priority: 4,
    isCustom: false,
  },
  {
    id: "contact-general",
    label: "Contacted",
    bgColor: "bg-yellow-100",
    textColor: "text-yellow-800",
    category: "contact",
    priority: 5,
    isCustom: false,
  },
]

export const mockData: CastingState = {
  projects: [
    {
      id: "proj_jurassic_park",
      name: "Jurassic Park - Remake",
      details: {
        type: "Feature Film",
        productionCompany: "Amblin Entertainment",
        director: "Steven Spielberg",
        producer: "Kathleen Kennedy, Gerald R. Molen",
        scriptLink: "#",
        description: "Steven Spielberg's dinosaur adventure film.",
      },
      createdDate: Date.now() - 14 * 24 * 60 * 60 * 1000,
      modifiedDate: Date.now() - 2 * 60 * 60 * 1000,
      projectUsers: [
        { userId: "userDS", permissionLevel: "producer" },
        { userId: "userCR", permissionLevel: "casting_director" },
        { userId: "userPV", permissionLevel: "admin" },
      ],
      characters: [
        {
          id: "grant",
          name: "Dr. Alan Grant",
          description: "A renowned paleontologist.",
          age: "40s",
          gender: "Male",
          ethnicity: "Caucasian",
          castingNotes:
            "Looking for someone who can balance scientific authority with action hero qualities. Age 40-55, must convey intelligence and rugged outdoorsmanship. Should be able to portray both skepticism and wonder.",
          actors: {
            longList: [
              {
                id: "neill",
                name: "Sam Neill",
                age: "40s",
                playingAge: "45-55",
                location: "NZ/UK",
                agent: "ICM",
                imdbUrl: "https://www.imdb.com/name/nm0000554/",
                skills: ["Paleontology", "Survivalist"],
                notes: [
                  {
                    userId: "userDS",
                    userName: "Director Spielberg",
                    timestamp: Date.now() - 100000,
                    text: "Top choice. Strong presence.",
                  },
                ],
                headshots: ["SamNeill", "SN_Profile", "SN_Action"],
                currentCardHeadshotIndex: 0,
                userVotes: {},
                consensusAction: undefined,
                isSoftRejected: false,
                isGreenlit: false,
                currentListKey: "longList",
                statuses: [
                  {
                    id: "contacted",
                    label: "Contacted",
                    bgColor: "bg-yellow-200",
                    textColor: "text-yellow-700",
                    isCustom: false,
                  },
                ],
                gender: "Male",
                ethnicity: "Caucasian",
                contactPhone: "+123456789",
                contactEmail: "sam.neill@example.com",
                availability: ["2025-07-01 to 2025-08-15"],
                mediaMaterials: [
                  {
                    name: "Drama Reel",
                    url: "https://example.com/sam-neill-reel",
                    taggedActorNames: ["Sam Neill"],
                  },
                ],
                showreels: [
                  {
                    name: "Drama Reel",
                    url: "https://www.youtube.com/watch?v=sample123",
                    taggedActorNames: ["Sam Neill"],
                  },
                ],
                auditionTapes: [],
                submissionVideos: [
                  {
                    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
                    platform: "youtube",
                  },
                  {
                    url: "https://vimeo.com/123456789",
                    embedUrl: "https://player.vimeo.com/video/123456789",
                    platform: "vimeo",
                  },
                ],
                vimeoVideos: [
                  {
                    id: "vimeo-sam-1",
                    url: "https://vimeo.com/123456789",
                    videoId: "123456789",
                    title: "Demo Reel",
                  },
                  {
                    id: "vimeo-sam-2",
                    url: "https://vimeo.com/987654321",
                    videoId: "987654321",
                    title: "Audition Tape",
                  },
                ],
              },
              {
                id: "goldblum",
                name: "Jeff Goldblum",
                age: "40s",
                playingAge: "40-50",
                location: "USA",
                agent: "WME",
                imdbUrl: "#",
                skills: ["Chaos Theory", "Jazz Piano"],
                notes: [
                  {
                    userId: "userCR",
                    userName: "Casting Robot",
                    timestamp: Date.now() - 150000,
                    text: "Could be Ian Malcolm, but let's see for Grant.",
                  },
                ],
                headshots: ["JeffG", "JG_Chaos"],
                currentCardHeadshotIndex: 0,
                userVotes: {},
                consensusAction: undefined,
                isSoftRejected: false,
                isGreenlit: false,
                currentListKey: "longList",
                statuses: [],
                gender: "Male",
                ethnicity: "Caucasian",
                contactPhone: "",
                contactEmail: "",
                availability: [],
                mediaMaterials: [],
                showreels: [],
                auditionTapes: [],
                submissionVideos: [
                  {
                    url: "https://www.youtube.com/watch?v=chaos123",
                    embedUrl: "https://www.youtube.com/embed/chaos123",
                    platform: "youtube",
                  },
                ],
                vimeoVideos: [
                  {
                    id: "vimeo-jeff-1",
                    url: "https://vimeo.com/456789123",
                    videoId: "456789123",
                    title: "Character Study",
                  },
                ],
              },
              {
                id: "hamill",
                name: "Mark Hamill",
                age: "40s",
                playingAge: "40-50",
                location: "USA",
                agent: "CAA",
                imdbUrl: "#",
                skills: ["Voice Acting"],
                notes: [
                  {
                    userId: "userPV",
                    userName: "Producer Vance",
                    timestamp: Date.now() - 200000,
                    text: "Interesting alternative, but maybe not quite right.",
                  },
                ],
                headshots: ["MarkHamill"],
                currentCardHeadshotIndex: 0,
                userVotes: {},
                consensusAction: undefined,
                isSoftRejected: false,
                isGreenlit: false,
                currentListKey: "longList",
                statuses: [],
                gender: "Male",
                ethnicity: "Caucasian",
                contactPhone: "",
                contactEmail: "",
                availability: [],
                mediaMaterials: [],
                showreels: [],
                auditionTapes: [],
                vimeoVideos: [],
              },
            ],
            shortLists: [
              {
                id: "sl1_grant",
                name: "Main Shortlist",
                actors: [
                  {
                    id: "hanks",
                    name: "Tom Hanks",
                    age: "60s",
                    playingAge: "55-65",
                    location: "USA",
                    agent: "CAA",
                    imdbUrl: "#",
                    skills: ["Versatile"],
                    notes: [
                      {
                        userId: "userCR",
                        userName: "Casting Robot",
                        timestamp: Date.now() - 50000,
                        text: "Classic choice, reliable.",
                      },
                      {
                        userId: "userDS",
                        userName: "Director Spielberg",
                        timestamp: Date.now() - 40000,
                        text: "Agreed, very bankable.",
                      },
                    ],
                    headshots: ["TomHanks"],
                    currentCardHeadshotIndex: 0,
                    userVotes: { userDS: "yes" },
                    consensusAction: undefined,
                    isSoftRejected: false,
                    isGreenlit: false,
                    currentListKey: "shortLists",
                    currentShortlistId: "sl1_grant",
                    statuses: [
                      {
                        id: "interested",
                        label: "Interested",
                        bgColor: "bg-blue-200",
                        textColor: "text-blue-700",
                        isCustom: false,
                      },
                    ],
                    gender: "Male",
                    ethnicity: "Caucasian",
                    contactPhone: "",
                    contactEmail: "",
                    availability: [],
                    mediaMaterials: [],
                    showreels: [],
                    auditionTapes: [],
                    vimeoVideos: [],
                  },
                ],
              },
            ],
            audition: [],
            approval: [
              {
                id: "pine",
                name: "Chris Pine",
                age: "40s",
                playingAge: "38-48",
                location: "USA",
                agent: "CAA",
                imdbUrl: "#",
                skills: ["Leading Man"],
                notes: [
                  {
                    userId: "userPV",
                    userName: "Producer Vance",
                    timestamp: Date.now(),
                    text: "Approved for consideration by PV.",
                  },
                ],
                headshots: ["ChrisP"],
                currentCardHeadshotIndex: 0,
                userVotes: {},
                consensusAction: undefined,
                isSoftRejected: false,
                isGreenlit: false,
                currentListKey: "approval",
                statuses: [],
                gender: "Male",
                ethnicity: "Caucasian",
                contactPhone: "",
                contactEmail: "",
                availability: [],
                mediaMaterials: [],
                showreels: [],
                auditionTapes: [],
                submissionVideos: [
                  {
                    url: "https://vimeo.com/pine123",
                    embedUrl: "https://player.vimeo.com/video/pine123",
                    platform: "vimeo",
                  },
                ],
                vimeoVideos: [
                  {
                    id: "vimeo-pine-1",
                    url: "https://vimeo.com/789123456",
                    videoId: "789123456",
                    title: "Action Reel",
                  },
                  {
                    id: "vimeo-pine-2",
                    url: "https://vimeo.com/234567890",
                    videoId: "234567890",
                    title: "Drama Scenes",
                  },
                ],
              },
            ],
          },
        },
        {
          id: "sattler",
          name: "Dr. Ellie Sattler",
          description: "A paleobotanist.",
          age: "30s",
          gender: "Female",
          ethnicity: "Caucasian",
          castingNotes: "Needs to be strong, intelligent, and resourceful.",
          actors: {
            longList: [],
            shortLists: [],
            audition: [],
            approval: [],
          },
        },
      ],
    },
  ],
  users: [
    {
      id: "userDS",
      name: "Director Spielberg",
      initials: "DS",
      email: "spielberg@example.com",
      role: "Director",
      color: "#1d4ed8",
      bgColor: "#dbeafe",
    },
    {
      id: "userCR",
      name: "Casting Robot",
      initials: "CR",
      email: "casting@example.com",
      role: "Casting Director",
      color: "#5b21b6",
      bgColor: "#ede9fe",
    },
    {
      id: "userPV",
      name: "Producer Vance",
      initials: "PV",
      email: "producer@example.com",
      role: "Producer",
      color: "#be185d",
      bgColor: "#fce7f3",
    },
  ],
  currentUser: null,
  cardViewSettings: {
    age: true,
    playingAge: true,
    agent: true,
    location: true,
    imdbUrl: true,
    skills: true,
    notes: true,
    showreels: true,
    auditionTapes: true,
    status: true,
    showVotes: true,
    showActionButtons: true,
  },
  currentFocus: {
    currentProjectId: "proj_jurassic_park",
    characterId: "grant",
    activeTabKey: "longList",
    activeShortlistId: null,
    cardDisplayMode: "detailed",
    currentSortOption: "alphabetical",
    searchTerm: "",
    playerView: {
      isOpen: false,
      currentIndex: 0,
      currentListKey: null,
      currentShortlistIdForPlayer: null,
      currentHeadshotIndex: 0,
    },
  },
  tabDefinitions: [
    { key: "longList", name: "Long List" },
    { key: "shortLists", name: "Shortlist" },
    { key: "audition", name: "Audition" },
    { key: "approval", name: "Approval" },
  ],
  viewOptionDefinitions: [
    { value: "detailed", label: "Detailed View" },
    { value: "simple", label: "Simple View" },
    { value: "list-view", label: "List View" },
    { value: "player", label: "Player View" },
  ],
  sortOptionDefinitions: [
    { value: "alphabetical", label: "Alphabetical (A-Z)" },
    { value: "consensus", label: "By Consensus" },
    { value: "status", label: "By Status" },
  ],
  predefinedStatuses,
  notifications: [],
  permissionLevels: [
    { id: "admin", label: "Producer", description: "Full access to all features, can manage users and settings." },
    {
      id: "casting_director",
      label: "Casting Director",
      description: "Can manage actors, auditions, and make casting decisions.",
    },
    { id: "producer", label: "Director", description: "Can view all data and approve final casting decisions." },
    { id: "viewer", label: "Viewer", description: "Read-only access to casting data." },
  ],
}

// Enhanced mock data with submission videos for testing
export const mockActorsWithVideos = [
  {
    id: "actor-1",
    name: "Emma Thompson",
    age: "28",
    playingAge: "25-30",
    location: "Los Angeles, CA",
    agent: "CAA",
    headshots: ["/placeholder.svg?height=300&width=240&text=ET"],
    currentCardHeadshotIndex: 0,
    userVotes: {},
    isSoftRejected: false,
    isGreenlit: false,
    isCast: false,
    currentListKey: "longList",
    statuses: [],
    dateAdded: Date.now() - 86400000,
    submissionVideos: [
      {
        url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        platform: "youtube",
      },
      {
        url: "https://vimeo.com/123456789",
        embedUrl: "https://player.vimeo.com/video/123456789",
        platform: "vimeo",
      },
    ],
  },
  {
    id: "actor-2",
    name: "Michael Chen",
    age: "32",
    playingAge: "30-35",
    location: "New York, NY",
    agent: "WME",
    headshots: ["/placeholder.svg?height=300&width=240&text=MC"],
    currentCardHeadshotIndex: 0,
    userVotes: {},
    isSoftRejected: false,
    isGreenlit: true,
    isCast: false,
    currentListKey: "audition",
    statuses: [],
    dateAdded: Date.now() - 172800000,
    submissionVideos: [
      {
        url: "https://www.youtube.com/watch?v=example123",
        embedUrl: "https://www.youtube.com/embed/example123",
        platform: "youtube",
      },
    ],
  },
]

// Function to add video data to existing actors
export const addVideoDataToActors = (actors: any[]) => {
  return actors.map((actor, index) => {
    // Add videos to some actors for testing
    if (index % 3 === 0) {
      return {
        ...actor,
        submissionVideos: [
          {
            url: `https://www.youtube.com/watch?v=test${index}`,
            embedUrl: `https://www.youtube.com/embed/test${index}`,
            platform: "youtube",
          },
        ],
      }
    } else if (index % 4 === 0) {
      return {
        ...actor,
        submissionVideos: [
          {
            url: `https://vimeo.com/test${index}`,
            embedUrl: `https://player.vimeo.com/video/test${index}`,
            platform: "vimeo",
          },
          {
            url: `https://www.youtube.com/watch?v=test${index}b`,
            embedUrl: `https://www.youtube.com/embed/test${index}b`,
            platform: "youtube",
          },
        ],
      }
    }
    return actor
  })
}
