// lib/mockData.ts

import type { CastingState } from "@/types/casting"

const predefinedStatuses = [
  {
    id: "new",
    label: "New",
    bgColor: "bg-gray-200",
    textColor: "text-gray-700",
    category: "application",
    priority: 1,
    isCustom: false,
  },
  {
    id: "applied",
    label: "Applied",
    bgColor: "bg-blue-200",
    textColor: "text-blue-700",
    category: "application",
    priority: 2,
    isCustom: false,
  },
  {
    id: "interviewing",
    label: "Interviewing",
    bgColor: "bg-purple-200",
    textColor: "text-purple-700",
    category: "application",
    priority: 3,
    isCustom: false,
  },
  {
    id: "offer",
    label: "Offer",
    bgColor: "bg-green-200",
    textColor: "text-green-700",
    category: "application",
    priority: 4,
    isCustom: false,
  },
  {
    id: "rejected",
    label: "Rejected",
    bgColor: "bg-red-200",
    textColor: "text-red-700",
    category: "application",
    priority: 5,
    isCustom: false,
  },
  {
    id: "closed",
    label: "Closed",
    bgColor: "bg-gray-400",
    textColor: "text-gray-900",
    category: "application",
    priority: 6,
    isCustom: false,
  },
  // Contact Status Categories
  {
    id: "contact-audition",
    label: "Audition Invited",
    bgColor: "bg-blue-100",
    textColor: "text-blue-800",
    category: "contact",
    priority: 1,
    isCustom: false,
  },
  {
    id: "contact-callback",
    label: "Callback Invited",
    bgColor: "bg-green-100",
    textColor: "text-green-800",
    category: "contact",
    priority: 2,
    isCustom: false,
  },
  {
    id: "contact-rejection",
    label: "Thanked",
    bgColor: "bg-gray-100",
    textColor: "text-gray-800",
    category: "contact",
    priority: 3,
    isCustom: false,
  },
  {
    id: "contact-offer",
    label: "Offer Sent",
    bgColor: "bg-purple-100",
    textColor: "text-purple-800",
    category: "contact",
    priority: 4,
    isCustom: false,
  },
  {
    id: "contact-general",
    label: "Contacted",
    bgColor: "bg-yellow-100",
    textColor: "text-yellow-800",
    category: "contact",
    priority: 5,
    isCustom: false,
  },
]

export const mockData: CastingState = {
  projects: [
    {
      id: "proj_jurassic_park",
      name: "Jurassic Park - Remake",
      details: {
        type: "Feature Film",
        productionCompany: "Amblin Entertainment",
        director: "Steven Spielberg",
        producer: "Kathleen Kennedy, Gerald R. Molen",
        scriptLink: "#",
        description: "Steven Spielberg's dinosaur adventure film.",
      },
      createdDate: Date.now() - 14 * 24 * 60 * 60 * 1000,
      modifiedDate: Date.now() - 2 * 60 * 60 * 1000,
      projectUsers: [
        { userId: "userDS", permissionLevel: "producer" },
        { userId: "userCR", permissionLevel: "casting_director" },
        { userId: "userPV", permissionLevel: "admin" },
      ],
      characters: [
        {
          id: "grant",
          name: "Dr. Alan Grant",
          description: "A renowned paleontologist.",
          age: "40s",
          gender: "Male",
          ethnicity: "Caucasian",
          castingNotes:
            "Looking for someone who can balance scientific authority with action hero qualities. Age 40-55, must convey intelligence and rugged outdoorsmanship. Should be able to portray both skepticism and wonder.",
          actors: {
            longList: [
              {
                id: "neill",
                name: "Sam Neill",
                age: "40s",
                playingAge: "45-55",
                location: "NZ/UK",
                agent: "ICM",
                imdbUrl: "https://www.imdb.com/name/nm0000554/",
                skills: ["Paleontology", "Survivalist"],
                notes: [
                  {
                    userId: "userDS",
                    userName: "Director Spielberg",
                    timestamp: Date.now() - 100000,
                    text: "Top choice. Strong presence.",
                  },
                ],
                headshots: ["SamNeill", "SN_Profile", "SN_Action"],
                currentCardHeadshotIndex: 0,
                userVotes: {},
                consensusAction: undefined,
                isSoftRejected: false,
                isGreenlit: false,
                currentListKey: "longList",
                statuses: [
                  {
                    id: "contacted",
                    label: "Contacted",
                    bgColor: "bg-yellow-200",
                    textColor: "text-yellow-700",
                    isCustom: false,
                  },
                ],
                gender: "Male",
                ethnicity: "Caucasian",
                contactPhone: "+123456789",
                contactEmail: "sam.neill@example.com",
                availability: ["2025-07-01 to 2025-08-15"],
                mediaMaterials: [
                  {
                    name: "Drama Reel",
                    url: "https://example.com/sam-neill-reel",
                    taggedActorNames: ["Sam Neill"],
                  },
                ],
                showreels: [
                  {
                    name: "Drama Reel",
                    url: "https://www.youtube.com/watch?v=sample123",
                    taggedActorNames: ["Sam Neill"],
                  },
                ],
                auditionTapes: [],
                submissionVideos: [
                  {
                    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
                    platform: "youtube",
                  },
                  {
                    url: "https://vimeo.com/123456789",
                    embedUrl: "https://player.vimeo.com/video/123456789",
                    platform: "vimeo",
                  },
                ],
                vimeoVideos: [
                  {
                    id: "vimeo-sam-1",
                    url: "https://vimeo.com/123456789",
                    videoId: "123456789",
                    title: "Demo Reel",
                  },
                  {
                    id: "vimeo-sam-2",
                    url: "https://vimeo.com/987654321",
                    videoId: "987654321",
                    title: "Audition Tape",
                  },
                ],
                messageHistory: [
                  {
                    id: "msg-neill-1",
                    direction: "outgoing" as const,
                    senderName: "Director Spielberg",
                    senderRole: "Director",
                    subject: "Audition Invitation - Dr. Alan Grant in Jurassic Park",
                    body: "Dear Sam,\n\nWe are pleased to invite you to audition for the role of Dr. Alan Grant in our upcoming production \"Jurassic Park\".\n\nAudition Details:\nDate: July 15, 2025\nTime: 10:00 AM\nLocation: Universal Studios, Stage 12\n\nPlease prepare a contemporary monologue (2-3 minutes). Sides will be provided upon arrival.\n\nWe look forward to seeing your audition.\n\nBest regards,\nDirector Spielberg",
                    timestamp: Date.now() - 7 * 24 * 60 * 60 * 1000,
                    templateUsed: "Invitation to Audition",
                    characterName: "Dr. Alan Grant",
                  },
                  {
                    id: "msg-neill-2",
                    direction: "incoming" as const,
                    senderName: "Sam Neill",
                    senderRole: "Actor",
                    subject: "Re: Audition Invitation - Dr. Alan Grant in Jurassic Park",
                    body: "Dear Director Spielberg,\n\nThank you so much for the invitation. I am very excited about the opportunity to audition for Dr. Alan Grant.\n\nI will be available on July 15 and will prepare accordingly. Could you let me know if there are any specific scenes or character notes I should review beforehand?\n\nLooking forward to it.\n\nBest regards,\nSam",
                    timestamp: Date.now() - 6 * 24 * 60 * 60 * 1000,
                    characterName: "Dr. Alan Grant",
                    read: true,
                  },
                  {
                    id: "msg-neill-3",
                    direction: "outgoing" as const,
                    senderName: "Director Spielberg",
                    senderRole: "Director",
                    subject: "Re: Audition Invitation - Dr. Alan Grant in Jurassic Park",
                    body: "Hi Sam,\n\nGreat to hear! For preparation, focus on the dig-site discovery scene - Grant's mix of scientific wonder and protective instinct is key to the character.\n\nWe'll have sides from Scenes 12 and 24 ready for you. Feel free to bring your own interpretation.\n\nSee you on the 15th!\n\nBest,\nSteven",
                    timestamp: Date.now() - 5 * 24 * 60 * 60 * 1000,
                    characterName: "Dr. Alan Grant",
                  },
                  {
                    id: "msg-neill-4",
                    direction: "incoming" as const,
                    senderName: "Sam Neill",
                    senderRole: "Actor (via ICM)",
                    subject: "Re: Audition Invitation - Dr. Alan Grant in Jurassic Park",
                    body: "Steven,\n\nPerfect, thank you for the guidance. I've been doing some reading on paleontology to get into the mindset. The dig-site scene sounds wonderful.\n\nQuick question from my agent at ICM - will there be a chemistry read with the actor cast as Dr. Sattler?\n\nThanks again,\nSam",
                    timestamp: Date.now() - 4 * 24 * 60 * 60 * 1000,
                    characterName: "Dr. Alan Grant",
                    read: true,
                  },
                  {
                    id: "msg-neill-5",
                    direction: "outgoing" as const,
                    senderName: "Casting Robot",
                    senderRole: "Casting Director",
                    subject: "Callback Invitation - Dr. Alan Grant",
                    body: "Dear Sam,\n\nCongratulations! We would like to invite you back for a callback audition for Dr. Alan Grant.\n\nCallback Details:\nDate: July 22, 2025\nTime: 2:00 PM\nLocation: Universal Studios, Stage 12\n\nYes, there will be a chemistry read with Laura Dern. Please prepare the raptor kitchen scene (Scene 42) in addition to the dig-site material.\n\nWe were very impressed with your initial audition.\n\nBest regards,\nCasting Team",
                    timestamp: Date.now() - 2 * 24 * 60 * 60 * 1000,
                    templateUsed: "Callback Invitation",
                    characterName: "Dr. Alan Grant",
                  },
                ],
              },
              {
                id: "goldblum",
                name: "Jeff Goldblum",
                age: "40s",
                playingAge: "40-50",
                location: "USA",
                agent: "WME",
                imdbUrl: "#",
                skills: ["Chaos Theory", "Jazz Piano"],
                notes: [
                  {
                    userId: "userCR",
                    userName: "Casting Robot",
                    timestamp: Date.now() - 150000,
                    text: "Could be Ian Malcolm, but let's see for Grant.",
                  },
                ],
                headshots: ["JeffG", "JG_Chaos"],
                currentCardHeadshotIndex: 0,
                userVotes: {},
                consensusAction: undefined,
                isSoftRejected: false,
                isGreenlit: false,
                currentListKey: "longList",
                statuses: [],
                gender: "Male",
                ethnicity: "Caucasian",
                contactPhone: "",
                contactEmail: "",
                availability: [],
                mediaMaterials: [],
                showreels: [],
                auditionTapes: [],
                submissionVideos: [
                  {
                    url: "https://www.youtube.com/watch?v=chaos123",
                    embedUrl: "https://www.youtube.com/embed/chaos123",
                    platform: "youtube",
                  },
                ],
                vimeoVideos: [
                  {
                    id: "vimeo-jeff-1",
                    url: "https://vimeo.com/456789123",
                    videoId: "456789123",
                    title: "Character Study",
                  },
                ],
                messageHistory: [
                  {
                    id: "msg-goldblum-1",
                    direction: "outgoing" as const,
                    senderName: "Casting Robot",
                    senderRole: "Casting Director",
                    subject: "Regarding Jurassic Park - Dr. Alan Grant",
                    body: "Dear Jeff,\n\nI hope this email finds you well. I am reaching out regarding our upcoming production \"Jurassic Park\".\n\nWe are considering you for the role of Dr. Alan Grant and would love to discuss the character with you. Are you available for an initial conversation next week?\n\nThank you for your time and consideration.\n\nBest regards,\nCasting Team",
                    timestamp: Date.now() - 10 * 24 * 60 * 60 * 1000,
                    templateUsed: "General Inquiry",
                    characterName: "Dr. Alan Grant",
                  },
                  {
                    id: "msg-goldblum-2",
                    direction: "incoming" as const,
                    senderName: "Jeff Goldblum",
                    senderRole: "Actor (via WME)",
                    subject: "Re: Regarding Jurassic Park - Dr. Alan Grant",
                    body: "Hello,\n\nThank you for reaching out. Jeff is very interested in the project, though we believe the role of Dr. Ian Malcolm might be a better fit for his particular style.\n\nWould the production be open to discussing that possibility? Jeff has some wonderful ideas about the chaos theory angle.\n\nPlease let us know.\n\nWarm regards,\nWME Talent Division",
                    timestamp: Date.now() - 9 * 24 * 60 * 60 * 1000,
                    characterName: "Dr. Alan Grant",
                    read: true,
                  },
                ],
              },
              {
                id: "hamill",
                name: "Mark Hamill",
                age: "40s",
                playingAge: "40-50",
                location: "USA",
                agent: "CAA",
                imdbUrl: "#",
                skills: ["Voice Acting"],
                notes: [
                  {
                    userId: "userPV",
                    userName: "Producer Vance",
                    timestamp: Date.now() - 200000,
                    text: "Interesting alternative, but maybe not quite right.",
                  },
                ],
                headshots: ["MarkHamill"],
                currentCardHeadshotIndex: 0,
                userVotes: {},
                consensusAction: undefined,
                isSoftRejected: false,
                isGreenlit: false,
                currentListKey: "longList",
                statuses: [],
                gender: "Male",
                ethnicity: "Caucasian",
                contactPhone: "",
                contactEmail: "",
                availability: [],
                mediaMaterials: [],
                showreels: [],
                auditionTapes: [],
                vimeoVideos: [],
              },
            ],
            shortLists: [
              {
                id: "sl1_grant",
                name: "Main Shortlist",
                actors: [
                  {
                    id: "hanks",
                    name: "Tom Hanks",
                    age: "60s",
                    playingAge: "55-65",
                    location: "USA",
                    agent: "CAA",
                    imdbUrl: "#",
                    skills: ["Versatile"],
                    notes: [
                      {
                        userId: "userCR",
                        userName: "Casting Robot",
                        timestamp: Date.now() - 50000,
                        text: "Classic choice, reliable.",
                      },
                      {
                        userId: "userDS",
                        userName: "Director Spielberg",
                        timestamp: Date.now() - 40000,
                        text: "Agreed, very bankable.",
                      },
                    ],
                    headshots: ["TomHanks"],
                    currentCardHeadshotIndex: 0,
                    userVotes: { userDS: "yes" },
                    consensusAction: undefined,
                    isSoftRejected: false,
                    isGreenlit: false,
                    currentListKey: "shortLists",
                    currentShortlistId: "sl1_grant",
                    statuses: [
                      {
                        id: "interested",
                        label: "Interested",
                        bgColor: "bg-blue-200",
                        textColor: "text-blue-700",
                        isCustom: false,
                      },
                    ],
                    gender: "Male",
                    ethnicity: "Caucasian",
                    contactPhone: "",
                    contactEmail: "",
                    availability: [],
                    mediaMaterials: [],
                    showreels: [],
                    auditionTapes: [],
                    vimeoVideos: [],
                  },
                ],
              },
            ],
            audition: [],
            approval: [
              {
                id: "pine",
                name: "Chris Pine",
                age: "40s",
                playingAge: "38-48",
                location: "USA",
                agent: "CAA",
                imdbUrl: "#",
                skills: ["Leading Man"],
                notes: [
                  {
                    userId: "userPV",
                    userName: "Producer Vance",
                    timestamp: Date.now(),
                    text: "Approved for consideration by PV.",
                  },
                ],
                headshots: ["ChrisP"],
                currentCardHeadshotIndex: 0,
                userVotes: {},
                consensusAction: undefined,
                isSoftRejected: false,
                isGreenlit: false,
                currentListKey: "approval",
                statuses: [],
                gender: "Male",
                ethnicity: "Caucasian",
                contactPhone: "",
                contactEmail: "",
                availability: [],
                mediaMaterials: [],
                showreels: [],
                auditionTapes: [],
                submissionVideos: [
                  {
                    url: "https://vimeo.com/pine123",
                    embedUrl: "https://player.vimeo.com/video/pine123",
                    platform: "vimeo",
                  },
                ],
                vimeoVideos: [
                  {
                    id: "vimeo-pine-1",
                    url: "https://vimeo.com/789123456",
                    videoId: "789123456",
                    title: "Action Reel",
                  },
                  {
                    id: "vimeo-pine-2",
                    url: "https://vimeo.com/234567890",
                    videoId: "234567890",
                    title: "Drama Scenes",
                  },
                ],
              },
            ],
          },
        },
        {
          id: "sattler",
          name: "Dr. Ellie Sattler",
          description: "A paleobotanist.",
          age: "30s",
          gender: "Female",
          ethnicity: "Caucasian",
          castingNotes: "Needs to be strong, intelligent, and resourceful.",
          actors: {
            longList: [],
            shortLists: [],
            audition: [],
            approval: [],
          },
        },
      ],
    },
    // Additional Dummy Project 2
    {
      id: "proj_midnight_chronicles",
      name: "The Midnight Chronicles",
      details: {
        type: "TV Series",
        productionCompany: "Stellar Productions",
        director: "Alexandra Mitchell",
        producer: "Benjamin Hartwell",
        scriptLink: "#",
        description: "A supernatural thriller series following investigators of paranormal phenomena.",
      },
      createdDate: Date.now() - 10 * 24 * 60 * 60 * 1000,
      modifiedDate: Date.now() - 1 * 60 * 60 * 1000,
      projectUsers: [{ userId: "userDS", permissionLevel: "producer" }],
      characters: [
        { id: "detective_morgan", name: "Detective Morgan Blake", description: "Lead investigator with psychic abilities", age: "35-40", gender: "Female", ethnicity: "Any", castingNotes: "Strong presence, mysterious aura", actors: { longList: [
          { id: "act_1", name: "Catherine Holloway", age: "38", playingAge: "35-40", location: "UK", agent: "ICM", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Female", ethnicity: "Caucasian" },
          { id: "act_2", name: "Samantha Reeves", age: "36", playingAge: "34-40", location: "USA", agent: "WME", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Female", ethnicity: "Caucasian" },
        ], shortLists: [], audition: [], approval: [] } },
        { id: "professor_gray", name: "Professor Harrison Gray", description: "Paranormal researcher and mentor", age: "55-65", gender: "Male", ethnicity: "Any", castingNotes: "Wise, authoritative", actors: { longList: [
          { id: "act_3", name: "Jonathan Whitmore", age: "58", playingAge: "55-65", location: "UK", agent: "CAA", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Male", ethnicity: "Caucasian" },
        ], shortLists: [], audition: [], approval: [] } },
        { id: "agent_chen", name: "Special Agent Chen Wei", description: "FBI liaison skeptical of paranormal", age: "30-35", gender: "Male", ethnicity: "Asian", castingNotes: "Grounded, analytical", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "oracle_luna", name: "Luna Ravencroft", description: "Mysterious fortune teller with genuine powers", age: "40-50", gender: "Female", ethnicity: "Any", castingNotes: "Enigmatic, ethereal", actors: { longList: [
          { id: "act_4", name: "Victoria Blackwood", age: "45", playingAge: "40-50", location: "USA", agent: "UTA", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Female", ethnicity: "Mixed" },
        ], shortLists: [], audition: [], approval: [] } },
        { id: "tech_specialist", name: "Marcus Fitzgerald", description: "Tech specialist and gadget expert", age: "25-30", gender: "Male", ethnicity: "Any", castingNotes: "Nerdy but charismatic", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "journalist_kim", name: "Journalist Kim Park", description: "Investigative reporter uncovering truth", age: "28-35", gender: "Female", ethnicity: "Korean", castingNotes: "Determined, resourceful", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "shadow_entity", name: "The Shadow Entity", description: "Main antagonist, supernatural being", age: "Ageless", gender: "Non-binary", ethnicity: "Any", castingNotes: "Voice work, motion capture", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "captain_ross", name: "Captain Beatrice Ross", description: "Police captain, skeptical ally", age: "45-55", gender: "Female", ethnicity: "African American", castingNotes: "Commanding, pragmatic", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
      ],
    },
    // Additional Dummy Project 3
    {
      id: "proj_desert_bloom",
      name: "Desert Bloom Rising",
      details: {
        type: "Feature Film",
        productionCompany: "Oasis Pictures",
        director: "Carlos Mendez",
        producer: "Sarah Wellington",
        scriptLink: "#",
        description: "A sweeping drama about a family vineyard in New Mexico during the 1960s.",
      },
      createdDate: Date.now() - 20 * 24 * 60 * 60 * 1000,
      modifiedDate: Date.now() - 3 * 60 * 60 * 1000,
      projectUsers: [{ userId: "userCR", permissionLevel: "casting_director" }],
      characters: [
        { id: "matriarch_elena", name: "Elena Montoya-Cruz", description: "Family matriarch, vineyard owner", age: "60-70", gender: "Female", ethnicity: "Hispanic", castingNotes: "Strong, dignified", actors: { longList: [
          { id: "act_5", name: "Isabella Rodriguez", age: "62", playingAge: "60-70", location: "Mexico", agent: "CAA", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Female", ethnicity: "Hispanic" },
          { id: "act_6", name: "Carmen Delgado", age: "65", playingAge: "60-70", location: "Spain", agent: "WME", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Female", ethnicity: "Hispanic" },
        ], shortLists: [], audition: [], approval: [] } },
        { id: "son_miguel", name: "Miguel Montoya Jr", description: "Rebellious eldest son", age: "30-35", gender: "Male", ethnicity: "Hispanic", castingNotes: "Conflicted, passionate", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "daughter_sofia", name: "Sofia Montoya-Chen", description: "Youngest daughter, college educated", age: "22-28", gender: "Female", ethnicity: "Hispanic/Asian", castingNotes: "Intelligent, forward-thinking", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "rival_landowner", name: "Theodore Blackstone", description: "Rival landowner and antagonist", age: "50-60", gender: "Male", ethnicity: "Caucasian", castingNotes: "Cold, calculating", actors: { longList: [
          { id: "act_7", name: "Richard Thornton", age: "55", playingAge: "50-60", location: "USA", agent: "UTA", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Male", ethnicity: "Caucasian" },
        ], shortLists: [], audition: [], approval: [] } },
        { id: "foreman_jose", name: "Jose Luis Hernandez", description: "Loyal vineyard foreman", age: "45-55", gender: "Male", ethnicity: "Hispanic", castingNotes: "Hardworking, wise", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "love_interest", name: "Rebecca Anderson", description: "Journalist documenting the region", age: "28-35", gender: "Female", ethnicity: "Caucasian", castingNotes: "Curious, empathetic", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "young_elena", name: "Young Elena Montoya", description: "Elena in flashback sequences", age: "25-30", gender: "Female", ethnicity: "Hispanic", castingNotes: "Must resemble older Elena", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "banker_wilson", name: "Charles Wilson III", description: "Bank manager threatening foreclosure", age: "40-50", gender: "Male", ethnicity: "Caucasian", castingNotes: "Bureaucratic, conflicted", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
      ],
    },
    // Additional Dummy Project 4
    {
      id: "proj_quantum_legacy",
      name: "Quantum Legacy Protocol",
      details: {
        type: "Sci-Fi Series",
        productionCompany: "Future Vision Studios",
        director: "Nina Yamamoto",
        producer: "David Sterling",
        scriptLink: "#",
        description: "Scientists discover time travel and must prevent a catastrophic future.",
      },
      createdDate: Date.now() - 5 * 24 * 60 * 60 * 1000,
      modifiedDate: Date.now() - 30 * 60 * 1000,
      projectUsers: [{ userId: "userPV", permissionLevel: "admin" }],
      characters: [
        { id: "dr_quantum", name: "Dr. Evelyn Quantum", description: "Brilliant physicist, project lead", age: "35-45", gender: "Female", ethnicity: "Any", castingNotes: "Genius-level intellect, driven", actors: { longList: [
          { id: "act_8", name: "Jennifer Ashworth", age: "40", playingAge: "35-45", location: "UK", agent: "ICM", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Female", ethnicity: "Caucasian" },
          { id: "act_9", name: "Michelle Tanaka", age: "38", playingAge: "35-45", location: "Japan/USA", agent: "CAA", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Female", ethnicity: "Asian" },
          { id: "act_10", name: "Priya Sharma-Jones", age: "42", playingAge: "38-48", location: "India/UK", agent: "WME", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Female", ethnicity: "South Asian" },
        ], shortLists: [], audition: [], approval: [] } },
        { id: "soldier_reyes", name: "Commander Marco Reyes", description: "Military liaison, protector", age: "35-40", gender: "Male", ethnicity: "Hispanic", castingNotes: "Strong, honorable", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "ai_nexus", name: "NEXUS (AI Character)", description: "Sentient AI assistant", age: "N/A", gender: "Non-binary", ethnicity: "N/A", castingNotes: "Voice role, motion capture", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "future_dictator", name: "Chancellor Viktor Kraine", description: "Future timeline antagonist", age: "50-60", gender: "Male", ethnicity: "Eastern European", castingNotes: "Menacing, charismatic", actors: { longList: [
          { id: "act_11", name: "Alexander Volkov", age: "52", playingAge: "50-60", location: "Russia/USA", agent: "UTA", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Male", ethnicity: "Eastern European" },
        ], shortLists: [], audition: [], approval: [] } },
        { id: "rebel_leader", name: "Zara Al-Rashid", description: "Future resistance leader", age: "28-35", gender: "Female", ethnicity: "Middle Eastern", castingNotes: "Fierce, inspiring", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "tech_prodigy", name: "Theodore Chen-Williams", description: "Young tech genius intern", age: "20-25", gender: "Male", ethnicity: "Mixed", castingNotes: "Eager, brilliant", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "ethics_officer", name: "Dr. Margaret Okonkwo", description: "Ethics board chairperson", age: "50-60", gender: "Female", ethnicity: "Nigerian", castingNotes: "Principled, wise", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "past_scientist", name: "Albert Rothschild", description: "1940s scientist in flashback", age: "40-50", gender: "Male", ethnicity: "Caucasian", castingNotes: "Period-accurate, tragic", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
      ],
    },
    // Additional Dummy Project 5
    {
      id: "proj_ocean_depths",
      name: "Secrets of Ocean Depths",
      details: {
        type: "Documentary Drama",
        productionCompany: "Blue Planet Films",
        director: "Marina Cousteau",
        producer: "James Attenborough",
        scriptLink: "#",
        description: "A dramatized documentary about deep-sea exploration and discovery.",
      },
      createdDate: Date.now() - 30 * 24 * 60 * 60 * 1000,
      modifiedDate: Date.now() - 5 * 60 * 60 * 1000,
      projectUsers: [{ userId: "userDS", permissionLevel: "producer" }],
      characters: [
        { id: "marine_biologist", name: "Dr. Coral Fitzgerald", description: "Lead marine biologist", age: "35-45", gender: "Female", ethnicity: "Any", castingNotes: "Passionate about ocean life", actors: { longList: [
          { id: "act_12", name: "Natalie Oceanside", age: "38", playingAge: "35-45", location: "Australia", agent: "CAA", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Female", ethnicity: "Caucasian" },
        ], shortLists: [], audition: [], approval: [] } },
        { id: "sub_pilot", name: "Captain Dmitri Volkov", description: "Submarine pilot, veteran explorer", age: "45-55", gender: "Male", ethnicity: "Russian", castingNotes: "Grizzled, experienced", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "tech_engineer", name: "Kenji Nakamura-Smith", description: "Submersible engineer", age: "30-40", gender: "Male", ethnicity: "Japanese/American", castingNotes: "Technical, resourceful", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "narrator_voice", name: "Narrator (Voice Over)", description: "Documentary narrator", age: "50-65", gender: "Male", ethnicity: "Any", castingNotes: "Warm, authoritative voice", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "funding_exec", name: "Victoria Pemberton", description: "Corporate funding executive", age: "40-50", gender: "Female", ethnicity: "British", castingNotes: "Polished, ambitious", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "crew_medic", name: "Dr. Samuel Okafor", description: "Ship's medical officer", age: "35-45", gender: "Male", ethnicity: "Nigerian", castingNotes: "Calm under pressure", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "rival_explorer", name: "Hans Richter-Mueller", description: "Rival expedition leader", age: "45-55", gender: "Male", ethnicity: "German", castingNotes: "Competitive, ruthless", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "young_intern", name: "Amelia Brightwater", description: "Enthusiastic research intern", age: "22-28", gender: "Female", ethnicity: "Any", castingNotes: "Wide-eyed, determined", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
      ],
    },
    // Additional Dummy Project 6
    {
      id: "proj_broadway_dreams",
      name: "Broadway Dreams Musical",
      details: {
        type: "Musical Film",
        productionCompany: "Spotlight Productions",
        director: "Thomas Kaplan",
        producer: "Rebecca Harmony",
        scriptLink: "#",
        description: "A musical about aspiring performers trying to make it on Broadway.",
      },
      createdDate: Date.now() - 15 * 24 * 60 * 60 * 1000,
      modifiedDate: Date.now() - 2 * 60 * 60 * 1000,
      projectUsers: [{ userId: "userCR", permissionLevel: "casting_director" }],
      characters: [
        { id: "lead_dancer", name: "Isabella Martinez-Cole", description: "Lead dancer protagonist", age: "22-28", gender: "Female", ethnicity: "Hispanic", castingNotes: "Triple threat required", actors: { longList: [
          { id: "act_13", name: "Valentina Rosario", age: "24", playingAge: "22-28", location: "USA", agent: "ICM", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Female", ethnicity: "Hispanic" },
          { id: "act_14", name: "Destiny Williams", age: "26", playingAge: "22-30", location: "USA", agent: "WME", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Female", ethnicity: "African American" },
        ], shortLists: [], audition: [], approval: [] } },
        { id: "composer_love", name: "Jonathan Silverstein", description: "Aspiring composer, love interest", age: "25-32", gender: "Male", ethnicity: "Jewish American", castingNotes: "Musical talent essential", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "broadway_legend", name: "Dame Penelope Ashford", description: "Aging Broadway legend", age: "65-75", gender: "Female", ethnicity: "British", castingNotes: "Iconic presence", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "rival_performer", name: "Cassandra Wellington", description: "Rival performer, antagonist", age: "25-30", gender: "Female", ethnicity: "Caucasian", castingNotes: "Beautiful but ruthless", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "dance_teacher", name: "Maestro Giovanni Rosetti", description: "Demanding dance instructor", age: "50-60", gender: "Male", ethnicity: "Italian", castingNotes: "Perfectionist, secretly kind", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "supportive_friend", name: "Marcus Washington-Lee", description: "Best friend and roommate", age: "24-30", gender: "Male", ethnicity: "African American", castingNotes: "Comic relief, loyal", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "casting_director", name: "Harriet Bloomfield", description: "Tough Broadway casting director", age: "45-55", gender: "Female", ethnicity: "Any", castingNotes: "Intimidating, fair", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "stage_manager", name: "Timothy O'Connell", description: "Veteran stage manager", age: "40-50", gender: "Male", ethnicity: "Irish American", castingNotes: "No-nonsense, experienced", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
      ],
    },
    // Additional Dummy Project 7
    {
      id: "proj_arctic_expedition",
      name: "Arctic Expedition Force",
      details: {
        type: "Action Adventure",
        productionCompany: "Glacier Films International",
        director: "Viktor Nordstrom",
        producer: "Elizabeth Frost",
        scriptLink: "#",
        description: "A team races to uncover an ancient artifact buried beneath Arctic ice.",
      },
      createdDate: Date.now() - 8 * 24 * 60 * 60 * 1000,
      modifiedDate: Date.now() - 45 * 60 * 1000,
      projectUsers: [{ userId: "userPV", permissionLevel: "admin" }],
      characters: [
        { id: "expedition_leader", name: "Commander Sarah Winterbourne", description: "Ex-military expedition leader", age: "35-45", gender: "Female", ethnicity: "British", castingNotes: "Athletic, commanding", actors: { longList: [
          { id: "act_15", name: "Charlotte Ironside", age: "38", playingAge: "35-45", location: "UK", agent: "CAA", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Female", ethnicity: "Caucasian" },
          { id: "act_16", name: "Freya Magnusson", age: "40", playingAge: "35-45", location: "Iceland", agent: "UTA", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Female", ethnicity: "Nordic" },
        ], shortLists: [], audition: [], approval: [] } },
        { id: "archaeologist", name: "Dr. Benjamin Hawthorne", description: "Archaeologist and historian", age: "40-50", gender: "Male", ethnicity: "American", castingNotes: "Indiana Jones type", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "ice_climber", name: "Nikolai Petrov-Jensen", description: "Expert ice climber and guide", age: "30-40", gender: "Male", ethnicity: "Russian/Danish", castingNotes: "Rugged, survival expert", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "tech_specialist_arctic", name: "Dr. Yuki Tanaka-Morrison", description: "Technology and communications specialist", age: "28-35", gender: "Female", ethnicity: "Japanese/American", castingNotes: "Tech-savvy, resourceful", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "corporate_villain", name: "Magnus Richter III", description: "Corporate antagonist", age: "50-60", gender: "Male", ethnicity: "German/American", castingNotes: "Wealthy, menacing", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "indigenous_guide", name: "Amka Nanoq Olsen", description: "Inuit guide with local knowledge", age: "35-45", gender: "Male", ethnicity: "Inuit/Danish", castingNotes: "Wise, connected to land", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "medic_arctic", name: "Dr. Helena Christensen", description: "Field medic and survival expert", age: "30-40", gender: "Female", ethnicity: "Scandinavian", castingNotes: "Calm, competent", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "mercenary_leader", name: "Viktor Krueger", description: "Leader of rival mercenary team", age: "40-50", gender: "Male", ethnicity: "Eastern European", castingNotes: "Threatening, tactical", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
      ],
    },
    // Additional Dummy Project 8
    {
      id: "proj_silicon_dreams",
      name: "Silicon Valley Dreams",
      details: {
        type: "Drama Series",
        productionCompany: "Tech Story Studios",
        director: "Amy Chen-Roberts",
        producer: "Michael Zuckerstein",
        scriptLink: "#",
        description: "The rise and fall of a tech startup during the dot-com boom.",
      },
      createdDate: Date.now() - 25 * 24 * 60 * 60 * 1000,
      modifiedDate: Date.now() - 6 * 60 * 60 * 1000,
      projectUsers: [{ userId: "userDS", permissionLevel: "producer" }],
      characters: [
        { id: "tech_founder", name: "Alexandra Chen-Morrison", description: "Visionary tech founder", age: "28-35", gender: "Female", ethnicity: "Chinese American", castingNotes: "Brilliant, driven", actors: { longList: [
          { id: "act_17", name: "Sophia Chen-Williams", age: "30", playingAge: "28-35", location: "USA", agent: "WME", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Female", ethnicity: "Asian American" },
          { id: "act_18", name: "Grace Liu-Thompson", age: "32", playingAge: "28-38", location: "USA/China", agent: "CAA", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Female", ethnicity: "Chinese American" },
        ], shortLists: [], audition: [], approval: [] } },
        { id: "cofounder", name: "Marcus Johnson-Patel", description: "Co-founder and CTO", age: "30-38", gender: "Male", ethnicity: "Mixed", castingNotes: "Technical genius, socially awkward", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "vc_investor", name: "Victoria Huntington III", description: "Venture capitalist", age: "45-55", gender: "Female", ethnicity: "Caucasian", castingNotes: "Powerful, calculating", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "marketing_guru", name: "Deshawn Williams-Cooper", description: "Marketing genius", age: "28-35", gender: "Male", ethnicity: "African American", castingNotes: "Charismatic, creative", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "rival_ceo", name: "Richard Thornberg-Smith", description: "Rival company CEO", age: "40-50", gender: "Male", ethnicity: "Caucasian", castingNotes: "Ruthless competitor", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "ethics_engineer", name: "Dr. Aisha Okonkwo-Williams", description: "Engineer with ethical concerns", age: "30-40", gender: "Female", ethnicity: "Nigerian American", castingNotes: "Principled, conflicted", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "journalist_tech", name: "Rebecca Sterling-White", description: "Tech journalist investigating company", age: "32-40", gender: "Female", ethnicity: "Caucasian", castingNotes: "Persistent, ethical", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "early_employee", name: "Timothy Nguyen-Martinez", description: "Loyal early employee", age: "25-32", gender: "Male", ethnicity: "Vietnamese/Hispanic", castingNotes: "Dedicated, overlooked", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
      ],
    },
    // Additional Dummy Project 9
    {
      id: "proj_victorian_mystery",
      name: "Victorian Mystery Society",
      details: {
        type: "Period Drama",
        productionCompany: "Heritage Films UK",
        director: "Benedict Worthington",
        producer: "Lady Catherine Ashford",
        scriptLink: "#",
        description: "A secret society investigates supernatural crimes in 1890s London.",
      },
      createdDate: Date.now() - 12 * 24 * 60 * 60 * 1000,
      modifiedDate: Date.now() - 4 * 60 * 60 * 1000,
      projectUsers: [{ userId: "userCR", permissionLevel: "casting_director" }],
      characters: [
        { id: "lady_detective", name: "Lady Arabella Thornwood", description: "Aristocrat turned detective", age: "28-35", gender: "Female", ethnicity: "British", castingNotes: "Elegant, sharp-witted", actors: { longList: [
          { id: "act_19", name: "Elizabeth Pemberton", age: "30", playingAge: "28-35", location: "UK", agent: "ICM", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Female", ethnicity: "Caucasian" },
          { id: "act_20", name: "Genevieve Ashworth", age: "32", playingAge: "28-38", location: "UK", agent: "CAA", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Female", ethnicity: "Caucasian" },
        ], shortLists: [], audition: [], approval: [] } },
        { id: "scotland_yard", name: "Inspector Reginald Blackwood", description: "Scotland Yard liaison", age: "40-50", gender: "Male", ethnicity: "British", castingNotes: "By-the-book, secretly supportive", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "occultist", name: "Professor Alistair Crowley-Smith", description: "Occult expert and researcher", age: "50-60", gender: "Male", ethnicity: "British", castingNotes: "Mysterious, knowledgeable", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "street_urchin", name: "Young Thomas Pickwick", description: "Street urchin informant", age: "12-16", gender: "Male", ethnicity: "British", castingNotes: "Clever, resourceful", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "maid_assistant", name: "Margaret O'Brien-Kelly", description: "Lady's maid and assistant", age: "25-35", gender: "Female", ethnicity: "Irish", castingNotes: "Loyal, brave", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "villain_mastermind", name: "Baron Heinrich von Richter", description: "Mastermind antagonist", age: "45-55", gender: "Male", ethnicity: "German/British", castingNotes: "Sophisticated evil", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "medium", name: "Madame Esmeralda Nightshade", description: "Psychic medium", age: "35-45", gender: "Female", ethnicity: "Romani", castingNotes: "Genuine abilities", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "butler", name: "Bartholomew Worthington", description: "Loyal family butler", age: "55-65", gender: "Male", ethnicity: "British", castingNotes: "Dignified, protective", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
      ],
    },
    // Additional Dummy Project 10
    {
      id: "proj_space_colony",
      name: "New Horizon Colony One",
      details: {
        type: "Sci-Fi Epic",
        productionCompany: "Stellar Horizons Films",
        director: "James Cameron Jr",
        producer: "Sigourney Weaver-Smith",
        scriptLink: "#",
        description: "Humanity's first interstellar colony faces unexpected challenges on an alien world.",
      },
      createdDate: Date.now() - 3 * 24 * 60 * 60 * 1000,
      modifiedDate: Date.now() - 15 * 60 * 1000,
      projectUsers: [{ userId: "userPV", permissionLevel: "admin" }],
      characters: [
        { id: "colony_commander", name: "Commander Elena Vasquez-Chen", description: "Colony mission commander", age: "40-50", gender: "Female", ethnicity: "Hispanic/Asian", castingNotes: "Strong leader, compassionate", actors: { longList: [
          { id: "act_21", name: "Maria Rodriguez-Santos", age: "45", playingAge: "40-50", location: "USA/Mexico", agent: "WME", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Female", ethnicity: "Hispanic" },
          { id: "act_22", name: "Angela Chen-Williams", age: "42", playingAge: "38-48", location: "USA", agent: "CAA", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Female", ethnicity: "Asian American" },
          { id: "act_23", name: "Naomi Okonkwo-Johnson", age: "44", playingAge: "40-50", location: "UK/Nigeria", agent: "UTA", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Female", ethnicity: "African" },
        ], shortLists: [], audition: [], approval: [] } },
        { id: "chief_scientist", name: "Dr. Henrik Johansson", description: "Chief xenobiologist", age: "45-55", gender: "Male", ethnicity: "Swedish", castingNotes: "Brilliant, eccentric", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "security_chief", name: "Major Kwame Asante-Williams", description: "Security forces commander", age: "35-45", gender: "Male", ethnicity: "Ghanaian/American", castingNotes: "Tactical, protective", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "pilot_ace", name: "Lieutenant Maya Petrova-Singh", description: "Ace shuttle pilot", age: "28-35", gender: "Female", ethnicity: "Russian/Indian", castingNotes: "Daring, skilled", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "engineer_genius", name: "Dr. Tobias Nakamura-Schmidt", description: "Chief engineer", age: "35-45", gender: "Male", ethnicity: "Japanese/German", castingNotes: "Problem-solver", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "medic_colony", name: "Dr. Fatima Al-Rashid-Jones", description: "Chief medical officer", age: "38-48", gender: "Female", ethnicity: "Middle Eastern/American", castingNotes: "Compassionate, skilled", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "ai_colony", name: "ATLAS (Colony AI)", description: "Colony's AI system", age: "N/A", gender: "Non-binary", ethnicity: "N/A", castingNotes: "Voice role, evolving personality", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "first_contact", name: "The Ambassador (Alien)", description: "First alien contact", age: "Unknown", gender: "Alien", ethnicity: "Alien", castingNotes: "Mo-cap and voice, otherworldly", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "colonist_leader", name: "Harrison Wells-Fitzgerald", description: "Civilian colonist leader", age: "45-55", gender: "Male", ethnicity: "African American", castingNotes: "Charismatic, political", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
      ],
    },
    // Additional Dummy Project 11
    {
      id: "proj_culinary_masters",
      name: "Culinary Masters Championship",
      details: {
        type: "Reality Competition",
        productionCompany: "Taste TV Productions",
        director: "Gordon Ramsay Jr",
        producer: "Martha Stewart-Williams",
        scriptLink: "#",
        description: "Elite chefs compete for the title of Culinary Master.",
      },
      createdDate: Date.now() - 18 * 24 * 60 * 60 * 1000,
      modifiedDate: Date.now() - 8 * 60 * 60 * 1000,
      projectUsers: [{ userId: "userDS", permissionLevel: "producer" }],
      characters: [
        { id: "host_chef", name: "Chef Pierre Dubois-Martin", description: "Head judge and host", age: "50-60", gender: "Male", ethnicity: "French", castingNotes: "Michelin-star chef, charismatic", actors: { longList: [
          { id: "act_24", name: "Antoine Beaumont", age: "55", playingAge: "50-60", location: "France/USA", agent: "ICM", headshots: [], currentCardHeadshotIndex: 0, userVotes: {}, isSoftRejected: false, isGreenlit: false, currentListKey: "longList", statuses: [], gender: "Male", ethnicity: "French" },
        ], shortLists: [], audition: [], approval: [] } },
        { id: "judge_pastry", name: "Chef Sakura Tanaka-Williams", description: "Pastry expert judge", age: "40-50", gender: "Female", ethnicity: "Japanese/American", castingNotes: "World-renowned pastry chef", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "judge_molecular", name: "Dr. Marcus Chen-Rodriguez", description: "Molecular gastronomy judge", age: "35-45", gender: "Male", ethnicity: "Chinese/Hispanic", castingNotes: "Innovative, scientific approach", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "competitor_1", name: "Isabella Santos-Moretti", description: "Brazilian-Italian fusion chef", age: "28-35", gender: "Female", ethnicity: "Brazilian/Italian", castingNotes: "Passionate, creative", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "competitor_2", name: "Kwame Asante-Johnson", description: "African cuisine specialist", age: "30-40", gender: "Male", ethnicity: "Ghanaian American", castingNotes: "Traditional with modern twist", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "competitor_3", name: "Mei Lin Wong-Patterson", description: "Chinese-American chef", age: "25-35", gender: "Female", ethnicity: "Chinese American", castingNotes: "Young prodigy", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "competitor_4", name: "Aleksei Volkov-Christensen", description: "Russian-Nordic fusion", age: "32-42", gender: "Male", ethnicity: "Russian/Danish", castingNotes: "Bold flavors", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
        { id: "floor_manager", name: "Samantha Brightwell-Torres", description: "Kitchen floor manager", age: "35-45", gender: "Female", ethnicity: "British/Hispanic", castingNotes: "Organized, calm under pressure", actors: { longList: [], shortLists: [], audition: [], approval: [] } },
      ],
    },
  ],
  users: [
    {
      id: "userDS",
      name: "Director Spielberg",
      initials: "DS",
      email: "spielberg@example.com",
      role: "Director",
      color: "#1d4ed8",
      bgColor: "#dbeafe",
    },
    {
      id: "userCR",
      name: "Casting Robot",
      initials: "CR",
      email: "casting@example.com",
      role: "Casting Director",
      color: "#5b21b6",
      bgColor: "#ede9fe",
    },
    {
      id: "userPV",
      name: "Producer Vance",
      initials: "PV",
      email: "producer@example.com",
      role: "Producer",
      color: "#be185d",
      bgColor: "#fce7f3",
    },
  ],
  currentUser: null,
  cardViewSettings: {
    age: true,
    playingAge: true,
    agent: true,
    location: true,
    imdbUrl: true,
    skills: true,
    notes: true,
    showreels: true,
    auditionTapes: true,
    status: true,
    showVotes: true,
    showActionButtons: true,
  },
  currentFocus: {
    currentProjectId: "proj_jurassic_park",
    characterId: "grant",
    activeTabKey: "longList",
    activeShortlistId: null,
    cardDisplayMode: "detailed",
    currentSortOption: "alphabetical",
    searchTerm: "",
    playerView: {
      isOpen: false,
      currentIndex: 0,
      currentListKey: null,
      currentShortlistIdForPlayer: null,
      currentHeadshotIndex: 0,
    },
  },
  tabDefinitions: [
    { key: "longList", name: "Long List" },
    { key: "shortLists", name: "Shortlist" },
    { key: "audition", name: "Audition" },
    { key: "approval", name: "Approval" },
  ],
  viewOptionDefinitions: [
    { value: "detailed", label: "Detailed View" },
    { value: "simple", label: "Simple View" },
    { value: "list-view", label: "List View" },
    { value: "player", label: "Player View" },
  ],
  sortOptionDefinitions: [
    { value: "alphabetical", label: "Alphabetical (A-Z)" },
    { value: "consensus", label: "By Consensus" },
    { value: "status", label: "By Status" },
  ],
  predefinedStatuses,
  notifications: [],
  permissionLevels: [
    { id: "admin", label: "Producer", description: "Full access to all features, can manage users and settings." },
    {
      id: "casting_director",
      label: "Casting Director",
      description: "Can manage actors, auditions, and make casting decisions.",
    },
    { id: "producer", label: "Director", description: "Can view all data and approve final casting decisions." },
    { id: "viewer", label: "Viewer", description: "Read-only access to casting data." },
  ],
}

// Enhanced mock data with submission videos for testing
export const mockActorsWithVideos = [
  {
    id: "actor-1",
    name: "Emma Thompson",
    age: "28",
    playingAge: "25-30",
    location: "Los Angeles, CA",
    agent: "CAA",
    headshots: ["/placeholder.svg?height=300&width=240&text=ET"],
    currentCardHeadshotIndex: 0,
    userVotes: {},
    isSoftRejected: false,
    isGreenlit: false,
    isCast: false,
    currentListKey: "longList",
    statuses: [],
    dateAdded: Date.now() - 86400000,
    submissionVideos: [
      {
        url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
        embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        platform: "youtube",
      },
      {
        url: "https://vimeo.com/123456789",
        embedUrl: "https://player.vimeo.com/video/123456789",
        platform: "vimeo",
      },
    ],
  },
  {
    id: "actor-2",
    name: "Michael Chen",
    age: "32",
    playingAge: "30-35",
    location: "New York, NY",
    agent: "WME",
    headshots: ["/placeholder.svg?height=300&width=240&text=MC"],
    currentCardHeadshotIndex: 0,
    userVotes: {},
    isSoftRejected: false,
    isGreenlit: true,
    isCast: false,
    currentListKey: "audition",
    statuses: [],
    dateAdded: Date.now() - 172800000,
    submissionVideos: [
      {
        url: "https://www.youtube.com/watch?v=example123",
        embedUrl: "https://www.youtube.com/embed/example123",
        platform: "youtube",
      },
    ],
  },
]

// Function to add video data to existing actors
export const addVideoDataToActors = (actors: any[]) => {
  return actors.map((actor, index) => {
    // Add videos to some actors for testing
    if (index % 3 === 0) {
      return {
        ...actor,
        submissionVideos: [
          {
            url: `https://www.youtube.com/watch?v=test${index}`,
            embedUrl: `https://www.youtube.com/embed/test${index}`,
            platform: "youtube",
          },
        ],
      }
    } else if (index % 4 === 0) {
      return {
        ...actor,
        submissionVideos: [
          {
            url: `https://vimeo.com/test${index}`,
            embedUrl: `https://player.vimeo.com/video/test${index}`,
            platform: "vimeo",
          },
          {
            url: `https://www.youtube.com/watch?v=test${index}b`,
            embedUrl: `https://www.youtube.com/embed/test${index}b`,
            platform: "youtube",
          },
        ],
      }
    }
    return actor
  })
}
