// lib/mockData.ts

import type { CastingState } from "@/types/casting"

const predefinedStatuses = [
  {
    id: "new",
    label: "New",
    bgColor: "bg-gray-200",
    textColor: "text-gray-700",
    category: "application",
    isCustom: false,
  },
  {
    id: "contacted",
    label: "Contacted",
    bgColor: "bg-blue-200",
    textColor: "text-blue-700",
    category: "contact",
    isCustom: false,
  },
  {
    id: "interested",
    label: "Interested",
    bgColor: "bg-green-200",
    textColor: "text-green-700",
    category: "application",
    isCustom: false,
  },
  {
    id: "callback",
    label: "Callback Scheduled",
    bgColor: "bg-purple-200",
    textColor: "text-purple-700",
    category: "contact",
    isCustom: false,
  },
]

export const mockData: CastingState = {
  users: [
    {
      id: "user1",
      name: "Steven Spielberg",
      initials: "SS",
      email: "spielberg@example.com",
      role: "Director",
      color: "#1d4ed8",
      bgColor: "#dbeafe",
    },
    {
      id: "user2",
      name: "Kathleen Kennedy",
      initials: "KK",
      email: "kennedy@example.com",
      role: "Producer",
      color: "#be185d",
      bgColor: "#fce7f3",
    },
    {
      id: "user3",
      name: "Deborah Aquila",
      initials: "DA",
      email: "aquila@example.com",
      role: "Casting Director",
      color: "#5b21b6",
      bgColor: "#ede9fe",
    },
  ],
  currentUser: null,
  projects: [
    {
      id: "proj_jurassic_park",
      name: "Jurassic Park - Remake",
      description:
        "A thrilling science fiction adventure about a theme park showcasing genetically engineered dinosaurs that breaks down with catastrophic results.",
      createdDate: 1704067200000,
      modifiedDate: 1735603200000,
      characters: [
        {
          id: "char_alan_grant",
          name: "Dr. Alan Grant",
          description:
            "A renowned paleontologist who is skeptical about the dinosaur park but becomes a hero during the disaster.",
          age: "40-50",
          gender: "Male",
          ethnicity: "Any",
          castingNotes:
            "Looking for someone with gravitas and scientific credibility. Must be able to convey both wonder and terror.",
          actors: {
            longList: [
              {
                id: "actor_sam_neill",
                name: "Sam Neill",
                age: "45",
                playingAge: "40-50",
                location: "New Zealand",
                agent: "ICM Partners",
                gender: "Male",
                ethnicity: "Caucasian",
                contactPhone: "+64 9 123 4567",
                contactEmail: "sam.neill@example.com",
                skills: ["Drama", "Action", "British Accent"],
                availability: ["2025-06-01 to 2025-09-30"],
                headshots: ["/placeholder.svg?height=400&width=300&text=Sam+Neill"],
                currentCardHeadshotIndex: 0,
                userVotes: {
                  user1: "yes",
                  user2: "yes",
                  user3: "yes",
                },
                isSoftRejected: false,
                isGreenlit: true,
                isCast: false,
                currentListKey: "longList",
                statuses: [
                  {
                    id: "status_interested",
                    label: "Interested",
                    bgColor: "bg-green-100",
                    textColor: "text-green-800",
                    category: "contact",
                    isCustom: false,
                  },
                ],
                notes: [
                  {
                    id: "note1",
                    userId: "user1",
                    userName: "Steven Spielberg",
                    timestamp: 1735603200000,
                    text: "Perfect choice for Grant. Has the right mix of intelligence and ruggedness.",
                  },
                ],
                dateAdded: 1704067200000,
                submissionVideos: [
                  {
                    url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
                    embedUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
                    platform: "youtube",
                  },
                ],
              },
            ],
            shortLists: [
              {
                id: "shortlist_grant_top",
                name: "Top Choices",
                description: "Our absolute top picks for Dr. Grant",
                createdAt: 1704153600000,
                actors: [
                  {
                    id: "actor_harrison_ford",
                    name: "Harrison Ford",
                    age: "52",
                    playingAge: "45-55",
                    location: "Los Angeles, CA",
                    agent: "CAA",
                    gender: "Male",
                    ethnicity: "Caucasian",
                    skills: ["Action", "Drama"],
                    headshots: ["/placeholder.svg?height=400&width=300&text=Harrison+Ford"],
                    currentCardHeadshotIndex: 0,
                    userVotes: {
                      user1: "yes",
                      user2: "maybe",
                    },
                    isSoftRejected: false,
                    isGreenlit: false,
                    isCast: false,
                    currentListKey: "shortLists",
                    currentShortlistId: "shortlist_grant_top",
                    statuses: [],
                    dateAdded: 1704153600000,
                  },
                ],
              },
            ],
            audition: [],
            approval: [],
          },
        },
        {
          id: "char_ellie_sattler",
          name: "Dr. Ellie Sattler",
          description: "A paleobotanist and Grant's colleague who is strong, intelligent, and resourceful.",
          age: "30-40",
          gender: "Female",
          ethnicity: "Any",
          castingNotes:
            "Need someone who can portray scientific expertise while being action-capable and emotionally grounded.",
          actors: {
            longList: [
              {
                id: "actor_laura_dern",
                name: "Laura Dern",
                age: "35",
                playingAge: "30-40",
                location: "Los Angeles, CA",
                agent: "UTA",
                gender: "Female",
                ethnicity: "Caucasian",
                skills: ["Drama", "Action", "Comedy"],
                headshots: ["/placeholder.svg?height=400&width=300&text=Laura+Dern"],
                currentCardHeadshotIndex: 0,
                userVotes: {
                  user1: "yes",
                  user2: "yes",
                  user3: "yes",
                },
                isSoftRejected: false,
                isGreenlit: true,
                isCast: false,
                currentListKey: "longList",
                statuses: [
                  {
                    id: "status_callback",
                    label: "Callback Scheduled",
                    bgColor: "bg-blue-100",
                    textColor: "text-blue-800",
                    category: "contact",
                    isCustom: false,
                  },
                ],
                dateAdded: 1704067200000,
              },
            ],
            shortLists: [],
            audition: [],
            approval: [],
          },
        },
        {
          id: "char_ian_malcolm",
          name: "Dr. Ian Malcolm",
          description:
            "A chaotician who warned about the dangers of the park and provides comic relief through his cynical wit.",
          age: "35-45",
          gender: "Male",
          ethnicity: "Any",
          castingNotes:
            "Must have excellent comedic timing and be able to deliver complex scientific concepts in an accessible way.",
          actors: {
            longList: [
              {
                id: "actor_jeff_goldblum",
                name: "Jeff Goldblum",
                age: "40",
                playingAge: "35-45",
                location: "Los Angeles, CA",
                agent: "WME",
                gender: "Male",
                ethnicity: "Caucasian",
                skills: ["Comedy", "Drama", "Jazz Piano"],
                headshots: ["/placeholder.svg?height=400&width=300&text=Jeff+Goldblum"],
                currentCardHeadshotIndex: 0,
                userVotes: {
                  user1: "yes",
                  user2: "yes",
                  user3: "yes",
                },
                isSoftRejected: false,
                isGreenlit: true,
                isCast: false,
                currentListKey: "longList",
                statuses: [],
                notes: [
                  {
                    id: "note_malcolm1",
                    userId: "user1",
                    userName: "Steven Spielberg",
                    timestamp: 1735603200000,
                    text: "Jeff brings exactly the quirky energy we need for Malcolm.",
                  },
                ],
                dateAdded: 1704067200000,
              },
            ],
            shortLists: [],
            audition: [],
            approval: [],
          },
        },
        {
          id: "char_john_hammond",
          name: "John Hammond",
          description: "The billionaire creator of Jurassic Park who believes his dream can be controlled.",
          age: "60-75",
          gender: "Male",
          ethnicity: "Any",
          castingNotes:
            "Need someone with warmth and charisma who can portray both childlike wonder and stubborn determination.",
          actors: {
            longList: [
              {
                id: "actor_richard_attenborough",
                name: "Richard Attenborough",
                age: "70",
                playingAge: "65-75",
                location: "London, UK",
                agent: "ICM Partners",
                gender: "Male",
                ethnicity: "Caucasian",
                skills: ["Drama", "British Accent"],
                headshots: ["/placeholder.svg?height=400&width=300&text=Richard+Attenborough"],
                currentCardHeadshotIndex: 0,
                userVotes: {
                  user1: "yes",
                  user2: "yes",
                },
                isSoftRejected: false,
                isGreenlit: true,
                isCast: false,
                currentListKey: "longList",
                statuses: [],
                dateAdded: 1704067200000,
              },
            ],
            shortLists: [],
            audition: [],
            approval: [],
          },
        },
      ],
    },
  ],
  notifications: [],
  tabDefinitions: [
    { key: "longList", name: "Long List", isCustom: false },
    { key: "shortLists", name: "Shortlist", isCustom: false },
    { key: "audition", name: "Audition", isCustom: false },
    { key: "approval", name: "Approval", isCustom: false },
  ],
  predefinedStatuses,
  permissionLevels: [
    {
      id: "admin",
      label: "Producer",
      description: "Full access to all features",
    },
    {
      id: "casting_director",
      label: "Casting Director",
      description: "Can manage actors and auditions",
    },
    {
      id: "producer",
      label: "Director",
      description: "Can view and approve casting decisions",
    },
    {
      id: "viewer",
      label: "Viewer",
      description: "Read-only access",
    },
  ],
  currentFocus: {
    currentProjectId: "proj_jurassic_park",
    characterId: "char_alan_grant",
    activeTabKey: "longList",
    cardDisplayMode: "detailed",
    currentSortOption: "alphabetical",
    searchTerm: "",
    searchTags: [],
    savedSearches: [],
    playerView: {
      isOpen: false,
      currentIndex: 0,
      currentHeadshotIndex: 0,
    },
  },
  modals: {},
  cardViewSettings: {
    age: true,
    playingAge: true,
    location: true,
    agent: true,
    imdbUrl: true,
    status: true,
    skills: true,
    notes: true,
    showVotes: true,
    showActionButtons: true,
    mediaAndNotes: true,
    showProgress: true,
    showTags: true,
  },
  sortOptionDefinitions: [
    { key: "alphabetical", label: "Alphabetical (A-Z)" },
    { key: "consensus", label: "By Consensus" },
    { key: "status", label: "By Status" },
  ],
  terminology: {
    actor: {
      singular: "Actor",
      plural: "Actors",
    },
    character: {
      singular: "Character",
      plural: "Characters",
    },
  },
  tabDisplayNames: {},
  scheduleEntries: [],
  productionPhases: [],
  scenes: [],
}
